In [1]:
import pandas as pd

In [2]:
local_systems = pd.read_csv('data/core/systems_cleaned.csv')

In [3]:
local_systems.columns

Index(['system_id', 'system_public_name', 'site_location',
       'timezone_or_utc_offset', 'latitude', 'longitude', 'elevation_m',
       'dc_capacity_kW', 'kg_climate', 'pvcz_composite', 'pvcz_t_rack',
       'pvcz_t_roof', 'pvcz_humidity', 'pvcz_wind', 'tracking', 'type',
       'azimuth', 'tilt', 'first_timestamp', 'last_timestamp', 'years',
       'number_records', 'dataset_size_mb', 'available_sensor_channels',
       'qa_status', 'qa_issue', 'first_year', 'is_prize_data',
       'is_lake_parquet_data', 'is_lake_csv_data', 'has_irrad_data',
       'has_power_data', 'has_ambient_temp_data', 'has_some_temp_data',
       'has_ac_data', 'has_dc_data', 'has_voltage_data', 'has_current_data'],
      dtype='str')

In [12]:
local_systems.shape

(1862, 38)

In [36]:
local_systems_slim = local_systems.drop_duplicates()

In [40]:
local_systems[local_systems['system_id'] == 1332].describe()

,system_id,latitude,longitude,elevation_m,dc_capacity_kW,pvcz_composite,pvcz_t_rack,pvcz_t_roof,pvcz_humidity,pvcz_wind,azimuth,tilt,years,number_records,dataset_size_mb,available_sensor_channels,first_year
count,2.0,2.0000,2.0000,2.0,2.000,2.0,2.0,2.0,2.0,2.0,2.0,2.000000,2.000,2.0,2.00,2.0,2.0
mean,1332.0,39.7388,-105.1732,1770.0,1153.488,12.0,2.0,4.0,1.0,3.0,180.0,38.385000,11.115,304151409.0,6961.47,26.0,2013.0
std,0.0,0.0000,0.0000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,30.568226,0.000,0.0,0.00,0.0,0.0
min,1332.0,39.7388,-105.1732,1770.0,1153.488,12.0,2.0,4.0,1.0,3.0,180.0,16.770000,11.115,304151409.0,6961.47,26.0,2013.0
25%,1332.0,39.7388,-105.1732,1770.0,1153.488,12.0,2.0,4.0,1.0,3.0,180.0,27.577500,11.115,304151409.0,6961.47,26.0,2013.0
50%,1332.0,39.7388,-105.1732,1770.0,1153.488,12.0,2.0,4.0,1.0,3.0,180.0,38.385000,11.115,304151409.0,6961.47,26.0,2013.0
75%,1332.0,39.7388,-105.1732,1770.0,1153.488,12.0,2.0,4.0,1.0,3.0,180.0,49.192500,11.115,304151409.0,6961.47,26.0,2013.0
max,1332.0,39.7388,-105.1732,1770.0,1153.488,12.0,2.0,4.0,1.0,3.0,180.0,60.000000,11.115,304151409.0,6961.47,26.0,2013.0

In [41]:
local_systems[local_systems['system_id'] == 4901].describe()

,system_id,latitude,longitude,elevation_m,dc_capacity_kW,pvcz_composite,pvcz_t_rack,pvcz_t_roof,pvcz_humidity,pvcz_wind,azimuth,tilt,years,number_records,dataset_size_mb,available_sensor_channels,first_year
count,2.0,2.0000,2.0000,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.000000,2.0,2.0000,2.0,2.00,2.0,2.0
mean,4901.0,39.1385,-77.2155,137.0,242.5,34.0,4.0,7.0,3.0,3.0,180.000000,5.0,3.6273,190271024.0,4354.96,100.0,2014.0
std,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,127.279221,0.0,0.0000,0.0,0.00,0.0,0.0
min,4901.0,39.1385,-77.2155,137.0,242.5,34.0,4.0,7.0,3.0,3.0,90.000000,5.0,3.6273,190271024.0,4354.96,100.0,2014.0
25%,4901.0,39.1385,-77.2155,137.0,242.5,34.0,4.0,7.0,3.0,3.0,135.000000,5.0,3.6273,190271024.0,4354.96,100.0,2014.0
50%,4901.0,39.1385,-77.2155,137.0,242.5,34.0,4.0,7.0,3.0,3.0,180.000000,5.0,3.6273,190271024.0,4354.96,100.0,2014.0
75%,4901.0,39.1385,-77.2155,137.0,242.5,34.0,4.0,7.0,3.0,3.0,225.000000,5.0,3.6273,190271024.0,4354.96,100.0,2014.0
max,4901.0,39.1385,-77.2155,137.0,242.5,34.0,4.0,7.0,3.0,3.0,270.000000,5.0,3.6273,190271024.0,4354.96,100.0,2014.0

In [38]:
local_systems_slim['system_id'].value_counts()

system_id
1332     2
4901     2
2        1
3        1
4        1
        ..
14760    1
14761    1
14762    1
14763    1
14764    1
Name: count, Length: 1860, dtype: int64

In [37]:
local_systems_slim.shape

(1862, 38)

In [3]:
prize_systems = local_systems[
    local_systems['is_prize_data']
]

In [7]:
prize_systems

,system_id,system_public_name,site_location,timezone_or_utc_offset,latitude,longitude,elevation_m,dc_capacity_kW,kg_climate,pvcz_composite,...,is_lake_parquet_data,is_lake_csv_data,has_irrad_data,has_power_data,has_ambient_temp_data,has_some_temp_data,has_ac_data,has_dc_data,has_voltage_data,has_current_data
154,2105,Maui Ocean Center,"Maui, HI",10,20.792530,-156.512000,10.0,110.0,Cfb,36,...,False,False,True,True,True,True,True,True,True,False
155,2107,Farm Solar Array,"Arbuckle, CA",PST8PDT,38.996306,-122.134111,10.0,893.0,Csa,33,...,False,False,True,True,True,True,True,True,True,True
160,7333,Shine On Solar Facility - 10sec,"Levis, CA",8,36.578000,-120.401600,330.1,205300.0,Bsk,34,...,False,False,True,True,True,True,True,True,True,True
162,9068,SR_CO,"Kersey, CO",7,40.386400,-104.551200,1407.0,4738.0,Bsk,12,...,False,False,True,True,True,True,True,True,True,True
163,9069,Simon Solar Farm,"Social Circle, GA",5,33.676200,-83.676000,330.1,33000.0,Cfa,35,...,False,False,True,True,True,True,True,True,True,True

In [33]:
prize_systems[['system_id', 'has_power_data', 'has_voltage_data', 'has_current_data', 'has_ambient_temp_data', 'has_irrad_data']]

,system_id,has_power_data,has_voltage_data,has_current_data,has_ambient_temp_data,has_irrad_data
154,2105,True,True,False,True,True
155,2107,True,True,True,True,True
160,7333,True,True,True,True,True
162,9068,True,True,True,True,True
163,9069,True,True,True,True,True

In [14]:
parquet_systems = local_systems[local_systems['is_lake_parquet_data']]

In [23]:
parquet_systems.shape

(158, 38)

In [25]:
parquet_systems['system_id'].value_counts()

system_id
1332    2
4901    2
2       1
3       1
4       1
       ..
1431    1
1432    1
1433    1
4902    1
4903    1
Name: count, Length: 156, dtype: int64

In [26]:
parquet_systems[parquet_systems['system_id'] == 1332]

,system_id,system_public_name,site_location,timezone_or_utc_offset,latitude,longitude,elevation_m,dc_capacity_kW,kg_climate,pvcz_composite,...,is_lake_parquet_data,is_lake_csv_data,has_irrad_data,has_power_data,has_ambient_temp_data,has_some_temp_data,has_ac_data,has_dc_data,has_voltage_data,has_current_data
107,1332,NREL Parking Garage,"Golden, CO",7,39.7388,-105.1732,1770.0,1153.488,BSk,12,...,True,True,False,True,False,False,True,True,True,True
108,1332,NREL Parking Garage,"Golden, CO",7,39.7388,-105.1732,1770.0,1153.488,BSk,12,...,True,True,False,True,False,False,True,True,True,True

In [22]:
parquet_systems[(parquet_systems['system_id'] >= 4901)
                & (parquet_systems['system_id'] <= 4903)]

,system_id,system_public_name,site_location,timezone_or_utc_offset,latitude,longitude,elevation_m,dc_capacity_kW,kg_climate,pvcz_composite,...,is_lake_parquet_data,is_lake_csv_data,has_irrad_data,has_power_data,has_ambient_temp_data,has_some_temp_data,has_ac_data,has_dc_data,has_voltage_data,has_current_data
156,4901,NIST_Canopy_1,Gaithersburg MD,5,39.1385,-77.2155,137.0,242.5,Cfa,34,...,True,True,True,True,True,True,True,True,True,True
157,4901,NIST_Canopy_1,Gaithersburg MD,5,39.1385,-77.2155,137.0,242.5,Cfa,34,...,True,True,True,True,True,True,True,True,True,True
158,4902,NIST_Ground_1,Gaithersburg MD,5,39.1319,-77.2141,138.0,270.7,Cfa,34,...,True,True,True,True,True,True,True,True,True,True
159,4903,NIST_Roof_1,Gaithersburg MD,5,39.1354,-77.2156,149.0,73.7,Cfa,34,...,True,True,True,True,True,True,True,True,True,True

In [20]:
parquet_systems[['has_some_temp_data', 'has_power_data', 'has_voltage_data', 'has_current_data', 'has_irrad_data']].value_counts()

has_some_temp_data  has_power_data  has_voltage_data  has_current_data  has_irrad_data
True                True            True              True              True              40
False               True            True              True              False             38
                                    False             True              False             35
                                                      False             False             17
True                True            False             False             True              16
                                    True              True              False              5
                                                      False             True               5
                                    False             True              False              1
                                                      False             False              1
Name: count, dtype: int64

In [17]:
parquet_systems.loc[0:4, ['system_id', 'has_irrad_data',
       'has_power_data', 'has_ambient_temp_data', 'has_some_temp_data',
       'has_ac_data', 'has_dc_data', 'has_voltage_data', 'has_current_data']]

,system_id,has_irrad_data,has_power_data,has_ambient_temp_data,has_some_temp_data,has_ac_data,has_dc_data,has_voltage_data,has_current_data
0,2,True,True,False,True,True,True,True,True
1,3,True,True,False,True,True,True,True,True
2,4,True,True,True,True,True,True,True,True
3,10,True,True,True,True,True,True,True,True
4,33,True,True,True,True,True,True,True,True

In [4]:
local_systems['has_power_data'].value_counts()

has_power_data
True     1859
False       3
Name: count, dtype: int64

In [29]:
csv_systems = local_systems[(local_systems['is_lake_csv_data'])
                            & ~(local_systems['is_lake_parquet_data'])]

In [30]:
csv_systems.shape

(1696, 38)

In [31]:
csv_systems['system_id'].value_counts()

system_id
10000    1
10001    1
10003    1
10005    1
10006    1
        ..
14760    1
14761    1
14762    1
14763    1
14764    1
Name: count, Length: 1696, dtype: int64

In [32]:
csv_systems[['has_some_temp_data', 'has_power_data', 'has_voltage_data', 'has_current_data', 'has_irrad_data']].value_counts()

has_some_temp_data  has_power_data  has_voltage_data  has_current_data  has_irrad_data
False               True            False             False             False             1454
True                True            True              False             False              240
                                                                        True                 2
Name: count, dtype: int64

In [8]:
local_systems_types = local_systems.loc[:, ['system_id', 'is_prize_data', 'is_lake_parquet_data',
                                            'is_lake_csv_data']]

In [9]:
local_systems_types[['is_prize_data', 'is_lake_parquet_data',
                                            'is_lake_csv_data']].value_counts()

is_prize_data  is_lake_parquet_data  is_lake_csv_data
False          False                 True                1696
               True                  True                 158
True           False                 False                  5
False          False                 False                  3
Name: count, dtype: int64

In [10]:
all_false = local_systems_types[
    (~local_systems_types['is_prize_data'])
    & (~local_systems_types['is_lake_parquet_data'])
    & (~local_systems_types['is_lake_csv_data'])
]

In [11]:
all_false

      system_id  is_prize_data  is_lake_parquet_data  is_lake_csv_data
161        7334          False                 False             False
1617      12423          False                 False             False
1619      12494          False                 False             False

In [9]:
my_times = local_systems[['first_timestamp']].value_counts(dropna=False)

In [10]:
local_systems_elec = local_systems.loc[
    :, ['system_id', 'has_ac_data', 'has_dc_data']
]

In [35]:
local_systems_elec.head()

   system_id  has_ac_data  has_dc_data
0          2         True         True
1          3         True         True
2          4         True         True
3         10         True         True
4         33         True         True

In [11]:
local_systems_elec['has_ac_data'].value_counts()

has_ac_data
True     1859
False       3
Name: count, dtype: int64

In [12]:
no_ac = local_systems_elec[
    ~local_systems_elec.loc[:, 'has_ac_data']
]
no_ac

      system_id  has_ac_data  has_dc_data
161        7334        False        False
1617      12423        False        False
1619      12494        False        False

In [14]:
local_systems_elec['has_dc_data'].value_counts()

has_dc_data
False    1562
True      300
Name: count, dtype: int64

In [5]:
local_systems[['has_voltage_data', 'has_current_data']].value_counts()

has_voltage_data  has_current_data
False             False               1491
True              False                248
                  True                  87
False             True                  36
Name: count, dtype: int64

In [6]:
local_systems['has_current_data'].value_counts()

has_current_data
False    1739
True      123
Name: count, dtype: int64

In [18]:
my_str = 'prepare' 
my_str[0].upper() + my_str[1:]

'Prepare'

In [3]:
local_systems['has_irrad_data'].value_counts()

has_irrad_data
False    1794
True       68
Name: count, dtype: int64