In [4]:
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
from pathlib import Path
from gen_variable_standard_static import metrics_search_for_two_fragments_df
from clean_and_collect_power_data_retry import Clean
from tqdm import tqdm
import pyarrow as pa
from datetime import timedelta, date

In [5]:
for package_choice in [np, pd, pa]:
    print(package_choice.__name__)
    print(package_choice.__version__)

numpy
2.3.5
pandas
3.0.0
pyarrow
23.0.0

In [6]:
systems_cleaned = pd.read_csv('../../../data/core/systems_cleaned.csv')
test_path = '../../../../data_ds_project/testing_yearly_parquet/'

In [7]:
metrics_dir = Path("../../../data/raw/parquet-metrics/")
metrics_pq = pq.ParquetDataset(metrics_dir)
metrics_df = metrics_pq.read().to_pandas()
metrics_id_set = set(metrics_df.system_id)

In [8]:
ac_power_metrics = metrics_search_for_two_fragments_df(metrics_df, 'ac', 'pow', 'and')
ac_power_systems = set(ac_power_metrics['system_id'])
two_years_days = 2 * 365
enough_data_systems = systems_cleaned[systems_cleaned['num_days_actual_records'] >= two_years_days]
enough_data_ids = set(enough_data_systems.system_id)
enough_data_parquet_power_systems = enough_data_ids.intersection(ac_power_systems)
enough_data_parquet_power_list = list(enough_data_parquet_power_systems)
enough_data_parquet_power_list.sort()

In [9]:
test_path = '../../../../data_ds_project/testing_yearly_parquet/'
# amend as necessary

For testing, just save locally (don't upload it, I think)

In [10]:
test_10 = Clean(10, test_path, systems_cleaned, None, './test_results_10_first/')

In [11]:
my_year = 2016
year_2016_data_basic = test_10.extract_years_data_parquet(my_year)
year_2016_data_standard = test_10.standardize_dataframe(year_2016_data_basic)
year_2016_data_rem = test_10.remove_small_values(year_2016_data_standard)
year_2016_good_days = test_10.keep_good_days_only(year_2016_data_rem)
year_2016_energy_readings = test_10.convert_to_energy_LRS(year_2016_good_days)

	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2016-01-01 00:00:00    -0.001732  2016
1      2016-01-01 00:01:00    -0.001776  2016
2      2016-01-01 00:02:00    -0.001721  2016
3      2016-01-01 00:03:00    -0.001743  2016
4      2016-01-01 00:04:00    -0.001687  2016
...                    ...          ...   ...
518820 2016-12-31 23:55:00    -0.001220  2016
518821 2016-12-31 23:56:00    -0.001254  2016
518822 2016-12-31 23:57:00    -0.001209  2016
518823 2016-12-31 23:58:00    -0.001309  2016
518824 2016-12-31 23:59:00    -0.001265  2016

[518825 rows x 3 columns]
                      time     power
0      2016-01-01 00:00:00 -0.001732
1      2016-01-01 00:01:00 -0.001776
2      2016-01-01 00:02:00 -0.001721
3      2016-01-01 00:03:00 -0.001743
4      2016-01-01 00:04:00 -0.001687
...                    ...       ...
518820 2016-12-31 23:55:00 -0.001220
518821 2016-12-31 23:56:00 -0.001254
518822 2016-12-31 23:57:00 -0.001209
518823 2016-12-31 23:58:00 -0.001309
518824 2016-12-31 23:59:00 -0.001265

[518825 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.12
       smaller_max = 1.12
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days

In [12]:
test_1200 = Clean(1200, test_path, systems_cleaned, 'inverter', './test_results_1200_i_renew/')

In [13]:
def part_by_part(clean_obj: Clean, year: int):
    try:
        year_data_basic = clean_obj.extract_years_data_parquet(year)
    except BaseException as e:
        print(f'Trouble with {clean_obj.system_id}, part {clean_obj.meter_or_inverter}, year {year}.')
        print(f'Trouble with extract_years_data_parquet')
        raise e
    try:
        year_data_standard = clean_obj.standardize_dataframe(year_data_basic)
    except BaseException as e:
        print(f'Trouble with {clean_obj.system_id}, part {clean_obj.meter_or_inverter}, year {year}.')
        print(f'Trouble with standardize_dataframe')
        raise e
    try:
        year_data_rem = clean_obj.remove_small_values(year_data_standard)
    except BaseException as e:
        print(f'Trouble with {clean_obj.system_id}, part {clean_obj.meter_or_inverter}, year {year}.')
        print(f'Trouble with remove_small_values')
        raise e
    try:
        year_data_good_days = clean_obj.keep_good_days_only(year_data_rem)
    except BaseException as e:
        print(f'Trouble with {clean_obj.system_id}, part {clean_obj.meter_or_inverter}, year {year}.')
        print(f'Trouble with keep_good_days_only (probably good_days).')
        raise e
    try:
        year_data_energy_readings = clean_obj.convert_to_energy_LRS(year_data_good_days)
    except BaseException as e:
        print(f'Trouble with {clean_obj.system_id}, part {clean_obj.meter_or_inverter}, year {year}.')
        print(f'Trouble with convert_to_energy_LRS')
        raise e
    return (year_data_basic, year_data_standard, year_data_rem, year_data_good_days, year_data_energy_readings)

In [15]:
test_1200_year_2012 = part_by_part(test_1200, 2012)

	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                     time  ac_power_kW_inverter  ac_power_kW_meter  year
0     2012-01-01 07:15:31                   NaN                NaN  2012
1     2012-01-01 07:20:31              0.000000                NaN  2012
2     2012-01-01 07:25:32              0.000210                NaN  2012
3     2012-01-01 07:30:32              0.017430                NaN  2012
4     2012-01-01 07:35:32              0.106918                NaN  2012
...                   ...                   ...                ...   ...
34004 2012-12-13 16:45:32              0.024229                NaN  2012
34005 2012-12-13 16:50:32              0.000000                NaN  2012
34006 2012-12-13 16:55:32              0.000000                NaN  2012
34007 2012-12-13 17:00:32              0.000000                NaN  2012
34008 2012-12-13 17:05:32              0.000000                NaN  2012

[34009 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                     time  ac_power_kW_inverter
0     2012-01-01 07:15:31                   NaN
1     2012-01-01 07:20:31              0.000000
2     2012-01-01 07:25:32              0.000210
3     2012-01-01 07:30:32              0.017430
4     2012-01-01 07:35:32              0.106918
...                   ...                   ...
34004 2012-12-13 16:45:32              0.024229
34005 2012-12-13 16:50:32              0.000000
34006 2012-12-13 16:55:32              0.000000
34007 2012-12-13 17:00:32              0.000000
34008 2012-12-13 17:05:32              0.000000

[34009 rows x 2 columns]
                     time     power
1     2012-01-01 07:20:31  0.000000
2     2012-01-01 07:25:32  0.000210
3     2012-01-01 07:30:32  0.017430
4     2012-01-01 07:35:32  0.106918
5     2012-01-01 07:40:32  0.203117
...                   ...       ...
34004 2012-12-13 16:45:32  0.024229
34005 2012-12-13 16:50:32  0.000000
34006 2012-12-13 16:55:32  0.000000
34007 2012-12-13 17:00:32  0.000000
34008 2012-12-13 17:05:32  0.000000

[33847 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 51.84
       smaller_max = 48.6627193
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days

In [16]:
data_1200_inv_bas, data_1200_inv_std, data_1200_inv_rem, data_1200_inv_good, data_1200_year_ener = test_1200_year_2012

In [ ]:
data_1200_inv_bas['ac_power_kW_inverter'].max()

np.float64(48.6627193)

In [ ]:
data_1200_inv_std

                     time     power
1     2012-01-01 07:20:31  0.000000
2     2012-01-01 07:25:32  0.000210
3     2012-01-01 07:30:32  0.017430
4     2012-01-01 07:35:32  0.106918
5     2012-01-01 07:40:32  0.203117
...                   ...       ...
34004 2012-12-13 16:45:32  0.024229
34005 2012-12-13 16:50:32  0.000000
34006 2012-12-13 16:55:32  0.000000
34007 2012-12-13 17:00:32  0.000000
34008 2012-12-13 17:05:32  0.000000

[33847 rows x 2 columns]

In [ ]:
data_1200_inv_rem

                     time     power
7     2012-01-01 07:50:32  0.590158
8     2012-01-01 07:55:32  1.115535
9     2012-01-01 08:00:32  1.692868
10    2012-01-01 08:05:32  2.239591
11    2012-01-01 08:10:33  2.888722
...                   ...       ...
33998 2012-12-13 16:15:31  1.936600
33999 2012-12-13 16:20:31  1.618567
34000 2012-12-13 16:25:31  1.291200
34001 2012-12-13 16:30:31  0.940933
34002 2012-12-13 16:35:32  0.600243

[29841 rows x 2 columns]

In [ ]:
systems_cleaned[systems_cleaned['system_id']==1200]

,system_id,system_public_name,site_location,timezone_or_utc_offset,latitude,longitude,elevation_m,dc_capacity_kW,kg_climate,pvcz_composite,...,has_power_data,has_current_data,has_voltage_data,has_ac_data,has_dc_data,module_type,simplified_type,system_source,num_days_actual_records,sample_year
11,1200,Distributed Sun - BWI Hilton,"Linthicum Heights, MD",America/New_York,39.1958,-76.6808,155.0,51.84,Cfa,34,...,True,True,True,True,True,mono-Si,monocrystalline_Si,PVDAQ General,3365,2011

In [ ]:
data_1200_inv_std

Empty DataFrame
Columns: [time, power]
Index: []

Quick loop

In [ ]:
for system_id in tqdm(enough_data_parquet_power_list):
    # grab columns from a blank year
    blank_year_pq = pq.ParquetDataset(
        f'{test_path}{system_id}/',
        filters = [('year', '==', 1990)]
    )
    blank_year_df = blank_year_pq.read().to_pandas()
    pow_cols = [col_name for col_name in blank_year_df.columns if ('pow' in col_name)]
    is_inv = any([('inv' in col_name) for col_name in pow_cols])
    is_met = any([('met' in col_name) for col_name in pow_cols])
    if is_inv and is_met:
        met_inv_inputs = ['inverter', 'meter']
        met_inv_names = met_inv_inputs
    elif is_inv:
        met_inv_inputs = ['inverter',]
        met_inv_names = met_inv_inputs
    elif is_met:
        met_inv_inputs = ['meter',]
        met_inv_names = met_inv_inputs
    else:
        met_inv_inputs = [None,]
        met_inv_names = ['unknown',]
    for j in range(len(met_inv_inputs)):
        met_or_inv = met_inv_inputs[j]
        met_or_inv_name = met_inv_names[j]
        system_cleaning_module = Clean(system_id, test_path, systems_cleaned,
                                       met_or_inv, 
                                       f'./test_results/')
        system_cleaning_module.clean_all_and_write_to_file()

  0%|          | 0/82 [00:00<?, ?it/s]

100%|██████████| 82/82 [02:30<00:00,  1.83s/it]

In [ ]:
good_timezone_systems = [4, 10, 33, 36, 50, 51, 1199, 1204, 1283, 1284, 1289, 1332, 4902, 4903]

In [ ]:
for system_id in good_timezone_systems:
    # grab columns from a blank year
    blank_year_pq = pq.ParquetDataset(
        f'{test_path}{system_id}/',
        filters = [('year', '==', 1990)]
    )
    blank_year_df = blank_year_pq.read().to_pandas()
    pow_cols = [col_name for col_name in blank_year_df.columns if ('pow' in col_name)]
    is_inv = any([('inv' in col_name) for col_name in pow_cols])
    is_met = any([('met' in col_name) for col_name in pow_cols])
    if is_inv and is_met:
        met_inv_inputs = ['inverter', 'meter']
        met_inv_names = met_inv_inputs
    elif is_inv:
        met_inv_inputs = ['inverter',]
        met_inv_names = met_inv_inputs
    elif is_met:
        met_inv_inputs = ['meter',]
        met_inv_names = met_inv_inputs
    else:
        met_inv_inputs = [None,]
        met_inv_names = ['unknown',]
    for j in range(len(met_inv_inputs)):
        met_or_inv = met_inv_inputs[j]
        met_or_inv_name = met_inv_names[j]
        system_cleaning_module = Clean(system_id, test_path, systems_cleaned,
                                       met_or_inv, 
                                       f'./test_results_b/')
        system_cleaning_module.clean_all_and_write_to_file()

Now processing system 4, year 2007.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                     time  ac_power_kW  year
0     2007-08-26 00:00:00    -0.000006  2007
1     2007-08-26 00:15:00    -0.000029  2007
2     2007-08-26 00:30:00    -0.000029  2007
3     2007-08-26 00:45:00    -0.000020  2007
4     2007-08-26 01:00:00    -0.000021  2007
...                   ...          ...   ...
10749 2007-12-31 22:45:00    -0.000095  2007
10750 2007-12-31 23:00:00    -0.000095  2007
10751 2007-12-31 23:15:00    -0.000095  2007
10752 2007-12-31 23:30:00    -0.000095  2007
10753 2007-12-31 23:45:00    -0.000095  2007

[10754 rows x 3 columns]
                     time     power
0     2007-08-26 00:00:00 -0.000006
1     2007-08-26 00:15:00 -0.000029
2     2007-08-26 00:30:00 -0.000029
3     2007-08-26 00:45:00 -0.000020
4     2007-08-26 01:00:00 -0.000021
...                   ...       ...
10749 2007-12-31 22:45:00 -0.000095
10750 2007-12-31 23:00:00 -0.000095
10751 2007-12-31 23:15:00 -0.000095
10752 2007-12-31 23:30:00 -0.000095
10753 2007-12-31 23:45:00 -0.000095

[10754 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2008.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                     time  ac_power_kW  year
0     2008-01-01 00:00:00    -0.000098  2008
1     2008-01-01 00:15:00    -0.000096  2008
2     2008-01-01 00:30:00    -0.000095  2008
3     2008-01-01 00:45:00    -0.000095  2008
4     2008-01-01 01:00:00    -0.000095  2008
...                   ...          ...   ...
34328 2008-12-31 22:45:00    -0.000095  2008
34329 2008-12-31 23:00:00    -0.000095  2008
34330 2008-12-31 23:15:00    -0.000095  2008
34331 2008-12-31 23:30:00    -0.000095  2008
34332 2008-12-31 23:45:00    -0.000095  2008

[34333 rows x 3 columns]
                     time     power
0     2008-01-01 00:00:00 -0.000098
1     2008-01-01 00:15:00 -0.000096
2     2008-01-01 00:30:00 -0.000095
3     2008-01-01 00:45:00 -0.000095
4     2008-01-01 01:00:00 -0.000095
...                   ...       ...
34328 2008-12-31 22:45:00 -0.000095
34329 2008-12-31 23:00:00 -0.000095
34330 2008-12-31 23:15:00 -0.000095
34331 2008-12-31 23:30:00 -0.000095
34332 2008-12-31 23:45:00 -0.000095

[34333 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2009.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                     time  ac_power_kW  year
0     2009-01-01 00:00:00    -0.000095  2009
1     2009-01-01 00:15:00    -0.000095  2009
2     2009-01-01 00:30:00    -0.000095  2009
3     2009-01-01 00:45:00    -0.000095  2009
4     2009-01-01 01:00:00    -0.000095  2009
...                   ...          ...   ...
14621 2009-06-03 08:30:00    -0.000032  2009
14622 2009-06-03 08:45:00    -0.000032  2009
14623 2009-06-03 09:00:00    -0.000032  2009
14624 2009-06-03 09:15:00    -0.000032  2009
14625 2009-06-03 09:30:00    -0.000032  2009

[14626 rows x 3 columns]
                     time     power
0     2009-01-01 00:00:00 -0.000095
1     2009-01-01 00:15:00 -0.000095
2     2009-01-01 00:30:00 -0.000095
3     2009-01-01 00:45:00 -0.000095
4     2009-01-01 01:00:00 -0.000095
...                   ...       ...
14621 2009-06-03 08:30:00 -0.000032
14622 2009-06-03 08:45:00 -0.000032
14623 2009-06-03 09:00:00 -0.000032
14624 2009-06-03 09:15:00 -0.000032
14625 2009-06-03 09:30:00 -0.000032

[14626 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2010.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2010-01-22 00:00:00     0.000071  2010
1      2010-01-22 00:01:00     0.000071  2010
2      2010-01-22 00:02:00     0.000044  2010
3      2010-01-22 00:03:00     0.000247  2010
4      2010-01-22 00:04:00     0.000192  2010
...                    ...          ...   ...
286941 2010-12-31 23:55:00     0.003491  2010
286942 2010-12-31 23:56:00     0.003577  2010
286943 2010-12-31 23:57:00     0.003383  2010
286944 2010-12-31 23:58:00     0.003512  2010
286945 2010-12-31 23:59:00     0.003728  2010

[286946 rows x 3 columns]
                      time     power
0      2010-01-22 00:00:00  0.000071
1      2010-01-22 00:01:00  0.000071
2      2010-01-22 00:02:00  0.000044
3      2010-01-22 00:03:00  0.000247
4      2010-01-22 00:04:00  0.000192
...                    ...       ...
286941 2010-12-31 23:55:00  0.003491
286942 2010-12-31 23:56:00  0.003577
286943 2010-12-31 23:57:00  0.003383
286944 2010-12-31 23:58:00  0.003512
286945 2010-12-31 23:59:00  0.003728

[286946 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2011.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2011-01-01 00:00:00     0.003598  2011
1      2011-01-01 00:01:00     0.003577  2011
2      2011-01-01 00:02:00     0.003512  2011
3      2011-01-01 00:03:00     0.003447  2011
4      2011-01-01 00:04:00     0.003598  2011
...                    ...          ...   ...
524806 2011-12-31 23:55:00     0.003337  2011
524807 2011-12-31 23:56:00     0.003381  2011
524808 2011-12-31 23:57:00     0.003402  2011
524809 2011-12-31 23:58:00     0.003273  2011
524810 2011-12-31 23:59:00     0.003488  2011

[524811 rows x 3 columns]
                      time     power
0      2011-01-01 00:00:00  0.003598
1      2011-01-01 00:01:00  0.003577
2      2011-01-01 00:02:00  0.003512
3      2011-01-01 00:03:00  0.003447
4      2011-01-01 00:04:00  0.003598
...                    ...       ...
524806 2011-12-31 23:55:00  0.003337
524807 2011-12-31 23:56:00  0.003381
524808 2011-12-31 23:57:00  0.003402
524809 2011-12-31 23:58:00  0.003273
524810 2011-12-31 23:59:00  0.003488

[524811 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2012.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2012-01-01 00:00:00     0.003381  2012
1      2012-01-01 00:01:00     0.003510  2012
2      2012-01-01 00:02:00     0.003316  2012
3      2012-01-01 00:03:00     0.003445  2012
4      2012-01-01 00:04:00     0.003381  2012
...                    ...          ...   ...
525313 2012-12-31 23:55:00     0.002639  2012
525314 2012-12-31 23:56:00     0.002621  2012
525315 2012-12-31 23:57:00     0.002636  2012
525316 2012-12-31 23:58:00     0.002630  2012
525317 2012-12-31 23:59:00     0.002626  2012

[525318 rows x 3 columns]
                      time     power
0      2012-01-01 00:00:00  0.003381
1      2012-01-01 00:01:00  0.003510
2      2012-01-01 00:02:00  0.003316
3      2012-01-01 00:03:00  0.003445
4      2012-01-01 00:04:00  0.003381
...                    ...       ...
525313 2012-12-31 23:55:00  0.002639
525314 2012-12-31 23:56:00  0.002621
525315 2012-12-31 23:57:00  0.002636
525316 2012-12-31 23:58:00  0.002630
525317 2012-12-31 23:59:00  0.002626

[525318 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2013.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2013-01-01 00:00:00     0.002604  2013
1      2013-01-01 00:01:00     0.002619  2013
2      2013-01-01 00:02:00     0.002625  2013
3      2013-01-01 00:03:00     0.002624  2013
4      2013-01-01 00:04:00     0.002624  2013
...                    ...          ...   ...
525119 2013-12-31 23:55:00     0.002813  2013
525120 2013-12-31 23:56:00     0.002832  2013
525121 2013-12-31 23:57:00     0.002829  2013
525122 2013-12-31 23:58:00     0.002862  2013
525123 2013-12-31 23:59:00     0.002841  2013

[525124 rows x 3 columns]
                      time     power
0      2013-01-01 00:00:00  0.002604
1      2013-01-01 00:01:00  0.002619
2      2013-01-01 00:02:00  0.002625
3      2013-01-01 00:03:00  0.002624
4      2013-01-01 00:04:00  0.002624
...                    ...       ...
525119 2013-12-31 23:55:00  0.002813
525120 2013-12-31 23:56:00  0.002832
525121 2013-12-31 23:57:00  0.002829
525122 2013-12-31 23:58:00  0.002862
525123 2013-12-31 23:59:00  0.002841

[525124 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2014.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2014-01-01 00:00:00     0.002818  2014
1      2014-01-01 00:01:00     0.002838  2014
2      2014-01-01 00:02:00     0.002847  2014
3      2014-01-01 00:03:00     0.002857  2014
4      2014-01-01 00:04:00     0.002816  2014
...                    ...          ...   ...
524089 2014-12-31 23:55:00     0.002638  2014
524090 2014-12-31 23:56:00     0.002646  2014
524091 2014-12-31 23:57:00     0.002657  2014
524092 2014-12-31 23:58:00     0.002656  2014
524093 2014-12-31 23:59:00     0.002654  2014

[524094 rows x 3 columns]
                      time     power
0      2014-01-01 00:00:00  0.002818
1      2014-01-01 00:01:00  0.002838
2      2014-01-01 00:02:00  0.002847
3      2014-01-01 00:03:00  0.002857
4      2014-01-01 00:04:00  0.002816
...                    ...       ...
524089 2014-12-31 23:55:00  0.002638
524090 2014-12-31 23:56:00  0.002646
524091 2014-12-31 23:57:00  0.002657
524092 2014-12-31 23:58:00  0.002656
524093 2014-12-31 23:59:00  0.002654

[524094 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2015.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2015-01-01 00:00:00     0.002639  2015
1      2015-01-01 00:01:00     0.002646  2015
2      2015-01-01 00:02:00     0.002646  2015
3      2015-01-01 00:03:00     0.002655  2015
4      2015-01-01 00:04:00     0.002664  2015
...                    ...          ...   ...
525595 2015-12-31 23:55:00     0.002669  2015
525596 2015-12-31 23:56:00     0.002646  2015
525597 2015-12-31 23:57:00     0.002661  2015
525598 2015-12-31 23:58:00     0.002661  2015
525599 2015-12-31 23:59:00     0.002673  2015

[525600 rows x 3 columns]
                      time     power
0      2015-01-01 00:00:00  0.002639
1      2015-01-01 00:01:00  0.002646
2      2015-01-01 00:02:00  0.002646
3      2015-01-01 00:03:00  0.002655
4      2015-01-01 00:04:00  0.002664
...                    ...       ...
525595 2015-12-31 23:55:00  0.002669
525596 2015-12-31 23:56:00  0.002646
525597 2015-12-31 23:57:00  0.002661
525598 2015-12-31 23:58:00  0.002661
525599 2015-12-31 23:59:00  0.002673

[525600 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2016.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2016-01-01 00:00:00     0.002658  2016
1      2016-01-01 00:01:00     0.002661  2016
2      2016-01-01 00:02:00     0.002666  2016
3      2016-01-01 00:03:00     0.002672  2016
4      2016-01-01 00:04:00     0.002651  2016
...                    ...          ...   ...
527034 2016-12-31 23:55:00     0.002916  2016
527035 2016-12-31 23:56:00     0.002941  2016
527036 2016-12-31 23:57:00     0.002957  2016
527037 2016-12-31 23:58:00     0.002924  2016
527038 2016-12-31 23:59:00     0.002955  2016

[527039 rows x 3 columns]
                      time     power
0      2016-01-01 00:00:00  0.002658
1      2016-01-01 00:01:00  0.002661
2      2016-01-01 00:02:00  0.002666
3      2016-01-01 00:03:00  0.002672
4      2016-01-01 00:04:00  0.002651
...                    ...       ...
527034 2016-12-31 23:55:00  0.002916
527035 2016-12-31 23:56:00  0.002941
527036 2016-12-31 23:57:00  0.002957
527037 2016-12-31 23:58:00  0.002924
527038 2016-12-31 23:59:00  0.002955

[527039 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2017.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2017-01-01 00:00:00     0.002928  2017
1      2017-01-01 00:01:00     0.002930  2017
2      2017-01-01 00:02:00     0.002921  2017
3      2017-01-01 00:03:00     0.002935  2017
4      2017-01-01 00:04:00     0.002935  2017
...                    ...          ...   ...
506705 2017-12-31 23:55:00     0.002660  2017
506706 2017-12-31 23:56:00     0.002668  2017
506707 2017-12-31 23:57:00     0.002675  2017
506708 2017-12-31 23:58:00     0.002660  2017
506709 2017-12-31 23:59:00     0.002667  2017

[506710 rows x 3 columns]
                      time     power
0      2017-01-01 00:00:00  0.002928
1      2017-01-01 00:01:00  0.002930
2      2017-01-01 00:02:00  0.002921
3      2017-01-01 00:03:00  0.002935
4      2017-01-01 00:04:00  0.002935
...                    ...       ...
506705 2017-12-31 23:55:00  0.002660
506706 2017-12-31 23:56:00  0.002668
506707 2017-12-31 23:57:00  0.002675
506708 2017-12-31 23:58:00  0.002660
506709 2017-12-31 23:59:00  0.002667

[506710 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 0.8694875
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2018.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2018-01-01 00:00:00     0.002669  2018
1      2018-01-01 00:01:00     0.002679  2018
2      2018-01-01 00:02:00     0.002674  2018
3      2018-01-01 00:03:00     0.002672  2018
4      2018-01-01 00:04:00     0.002676  2018
...                    ...          ...   ...
392269 2018-12-14 05:19:00     0.002761  2018
392270 2018-12-14 05:20:00     0.002769  2018
392271 2018-12-14 05:21:00     0.002796  2018
392272 2018-12-14 05:22:00     0.002793  2018
392273 2018-12-14 05:23:00     0.002776  2018

[392274 rows x 3 columns]
                      time     power
0      2018-01-01 00:00:00  0.002669
1      2018-01-01 00:01:00  0.002679
2      2018-01-01 00:02:00  0.002674
3      2018-01-01 00:03:00  0.002672
4      2018-01-01 00:04:00  0.002676
...                    ...       ...
392269 2018-12-14 05:19:00  0.002761
392270 2018-12-14 05:20:00  0.002769
392271 2018-12-14 05:21:00  0.002796
392272 2018-12-14 05:22:00  0.002793
392273 2018-12-14 05:23:00  0.002776

[392274 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2019.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2019-01-29 16:11:00     0.339824  2019
1      2019-01-29 16:12:00     0.335248  2019
2      2019-01-29 16:13:00     0.331512  2019
3      2019-01-29 16:14:00     0.325340  2019
4      2019-01-29 16:15:00     0.304929  2019
...                    ...          ...   ...
419334 2019-12-17 09:37:00     0.726350  2019
419335 2019-12-17 09:38:00     0.726350  2019
419336 2019-12-17 09:39:00     0.726350  2019
419337 2019-12-17 09:40:00     0.726350  2019
419338 2019-12-17 09:41:00     0.726350  2019

[419339 rows x 3 columns]
                      time     power
0      2019-01-29 16:11:00  0.339824
1      2019-01-29 16:12:00  0.335248
2      2019-01-29 16:13:00  0.331512
3      2019-01-29 16:14:00  0.325340
4      2019-01-29 16:15:00  0.304929
...                    ...       ...
419334 2019-12-17 09:37:00  0.726350
419335 2019-12-17 09:38:00  0.726350
419336 2019-12-17 09:39:00  0.726350
419337 2019-12-17 09:40:00  0.726350
419338 2019-12-17 09:41:00  0.726350

[419339 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 1.0
       smaller_max = 1.0
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
float64
delta_t_mode data type = float64
delta_t_hours data type post-interpolation = float64
		span_flag done
	ending good_days
Now processing system 4, year 2020.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW  year
0      2020-01-23 09:50:00     0.139356  2020
1      2020-01-23 09:51:00     0.147297  2020
2      2020-01-23 09:52:00     0.149995  2020
3      2020-01-23 09:53:00     0.138965  2020
4      2020-01-23 09:54:00     0.130585  2020
...                    ...          ...   ...
477521 2020-12-31 23:55:00     0.002772  2020
477522 2020-12-31 23:56:00     0.002786  2020
477523 2020-12-31 23:57:00     0.002769  2020
477524 2020-12-31 23:58:00     0.002795  2020
477525 2020-12-31 23:59:00     0.002792  2020

[477526 rows x 3 columns]
                      time     power
0      2020-01-23 09:50:00  0.139356
1      2020-01-23 09:51:00  0.147297
2      2020-01-23 09:52:00  0.149995
3      2020-01-23 09:53:00  0.138965
4      2020-01-23 09:54:00  0.130585
...                    ...       ...
477521 2020-12-31 23:55:00  0.002772
477522 2020-12-31 23:56:00  0.002786
477523 2020-12-31 23:57:00  0.002769
477524 2020-12-31 23:58:00  0.002795
477525 2020-12-31 23:59:00  0.002792


In [ ]:
def good_runs(my_dates):
    runs_list = []
    num_dates = len(my_dates)
    if num_dates == 0:
        return []
    elif num_dates == 1:
        return [my_dates,]
    else:
        dates_ser = pd.Series(
            data = my_dates,
            name = 'date',
        )
        dates_ser = dates_ser.sort_values()
        dates_df = pd.DataFrame(dates_ser)
        dates_df.loc[:, 'forward_diff'] = -dates_df['date'].diff(periods=-1)
        dates_df.loc[:, 'good_forward'] = dates_df.apply(
            lambda row: row['forward_diff'] == timedelta(days=1),
            axis=1
        )
        end_runs = dates_df[~dates_df['good_forward']]
        num_runs = end_runs.shape[0]
        for j in range(num_runs):
            if j == 0:
                start_ind = 0
            else:
                start_ind = end_runs.index[j-1] + 1
            end_ind = end_runs.index[j]
            jth_run = dates_df.loc[start_ind:end_ind]
            runs_list.append(sorted(jth_run['date']))
        return runs_list

In [ ]:
def good_runs_series(dates_ser):
    runs_list = []
    num_dates = len(dates_ser)
    if num_dates == 0:
        return []
    elif num_dates == 1:
        return [[dates_ser.at[0],],]
    else:
        dates_ser = dates_ser.sort_values()
        dates_df = pd.DataFrame(dates_ser)
        dates_df.loc[:, 'forward_diff'] = -dates_df['date'].diff(periods=-1)
        dates_df.loc[:, 'good_forward'] = dates_df.apply(
            lambda row: row['forward_diff'] == timedelta(days=1),
            axis=1
        )
        end_runs = dates_df[~dates_df['good_forward']]
        num_runs = end_runs.shape[0]
        for j in range(num_runs):
            if j == 0:
                start_ind = 0
            else:
                start_ind = end_runs.index[j-1] + 1
            end_ind = end_runs.index[j]
            jth_run = dates_df.loc[start_ind:end_ind]
            runs_list.append(sorted(jth_run['date']))
        return runs_list

In [ ]:
test_read = pd.read_csv('./test_results_b/good_days/4_good_days_None.csv')

In [ ]:
type(test_read)

pandas.DataFrame

In [ ]:
test_read = test_read['date']

In [ ]:
test_read.head()

0    2007-09-01
1    2007-09-03
2    2007-09-04
3    2007-09-07
4    2007-09-08
Name: date, dtype: str

In [ ]:
test_read = test_read.astype('datetime[s]')

TypeError: data type 'datetime[s]' not understood

In [ ]:
test_read

0      2007-09-01
1      2007-09-03
2      2007-09-04
3      2007-09-07
4      2007-09-08
          ...
2887   2023-02-20
2888   2023-02-21
2889   2023-02-26
2890   2023-02-27
2891   2023-02-28
Name: date, Length: 2892, dtype: datetime64[s]

In [ ]:
test_read.dtype

In [ ]:
good_runs_series(test_read)

[[Timestamp('2007-09-01 00:00:00')],
 [Timestamp('2007-09-03 00:00:00'), Timestamp('2007-09-04 00:00:00')],
 [Timestamp('2007-09-07 00:00:00'), Timestamp('2007-09-08 00:00:00')],
 [Timestamp('2007-09-11 00:00:00'),
  Timestamp('2007-09-12 00:00:00'),
  Timestamp('2007-09-13 00:00:00'),
  Timestamp('2007-09-14 00:00:00'),
  Timestamp('2007-09-15 00:00:00')],
 [Timestamp('2007-09-18 00:00:00'), Timestamp('2007-09-19 00:00:00')],
 [Timestamp('2007-09-21 00:00:00'),
  Timestamp('2007-09-22 00:00:00'),
  Timestamp('2007-09-23 00:00:00')],
 [Timestamp('2007-09-25 00:00:00'),
  Timestamp('2007-09-26 00:00:00'),
  Timestamp('2007-09-27 00:00:00'),
  Timestamp('2007-09-28 00:00:00'),
  Timestamp('2007-09-29 00:00:00'),
  Timestamp('2007-09-30 00:00:00'),
  Timestamp('2007-10-01 00:00:00'),
  Timestamp('2007-10-02 00:00:00'),
  Timestamp('2007-10-03 00:00:00'),
  Timestamp('2007-10-04 00:00:00'),
  Timestamp('2007-10-05 00:00:00'),
  Timestamp('2007-10-06 00:00:00')],
 [Timestamp('2007-10-08 00:00:00'),
  Timestamp('2007-10-09 00:00:00'),
  Timestamp('2007-10-10 00:00:00'),
  Timestamp('2007-10-11 00:00:00'),
  Timestamp('2007-10-12 00:00:00')],
 [Timestamp('2007-10-15 00:00:00'),
  Timestamp('2007-10-16 00:00:00'),
  Timestamp('2007-10-17 00:00:00'),
  Timestamp('2007-10-18 00:00:00'),
  Timestamp('2007-10-19 00:00:00'),
  Timestamp('2007-10-20 00:00:00')],
 [Timestamp('2007-10-22 00:00:00'),
  Timestamp('2007-10-23 00:00:00'),
  Timestamp('2007-10-24 00:00:00'),
  Timestamp('2007-10-25 00:00:00'),
  Timestamp('2007-10-26 00:00:00'),
  Timestamp('2007-10-27 00:00:00'),
  Timestamp('2007-10-28 00:00:00'),
  Timestamp('2007-10-29 00:00:00'),
  Timestamp('2007-10-30 00:00:00'),
  Timestamp('2007-10-31 00:00:00'),
  Timestamp('2007-11-01 00:00:00'),
  Timestamp('2007-11-02 00:00:00'),
  Timestamp('2007-11-03 00:00:00'),
  Timestamp('2007-11-04 00:00:00'),
  Timestamp('2007-11-05 00:00:00'),
  Timestamp('2007-11-06 00:00:00'),
  Timestamp('2007-11-07 00:00:00'),
  Timestamp('2007-11-08 00:00:00'),
  Timestamp('2007-11-09 00:00:00'),
  Timestamp('2007-11-10 00:00:00'),
  Timestamp('2007-11-11 00:00:00'),
  Timestamp('2007-11-12 00:00:00'),
  Timestamp('2007-11-13 00:00:00'),
  Timestamp('2007-11-14 00:00:00'),
  Timestamp('2007-11-15 00:00:00'),
  Timestamp('2007-11-16 00:00:00')],
 [Timestamp('2007-11-18 00:00:00'), Timestamp('2007-11-19 00:00:00')],
 [Timestamp('2007-11-24 00:00:00'),
  Timestamp('2007-11-25 00:00:00'),
  Timestamp('2007-11-26 00:00:00'),
  Timestamp('2007-11-27 00:00:00')],
 [Timestamp('2007-11-29 00:00:00'), Timestamp('2007-11-30 00:00:00')],
 [Timestamp('2007-12-02 00:00:00'), Timestamp('2007-12-03 00:00:00')],
 [Timestamp('2007-12-20 00:00:00')],
 [Timestamp('2007-12-22 00:00:00'),
  Timestamp('2007-12-23 00:00:00'),
  Timestamp('2007-12-24 00:00:00')],
 [Timestamp('2007-12-30 00:00:00'), Timestamp('2007-12-31 00:00:00')],
 [Timestamp('2008-01-02 00:00:00'),
  Timestamp('2008-01-03 00:00:00'),
  Timestamp('2008-01-04 00:00:00'),
  Timestamp('2008-01-05 00:00:00'),
  Timestamp('2008-01-06 00:00:00')],
 [Timestamp('2008-01-09 00:00:00'), Timestamp('2008-01-10 00:00:00')],
 [Timestamp('2008-01-12 00:00:00'),
  Timestamp('2008-01-13 00:00:00'),
  Timestamp('2008-01-14 00:00:00')],
 [Timestamp('2008-01-17 00:00:00')],
 [Timestamp('2008-01-19 00:00:00')],
 [Timestamp('2008-01-22 00:00:00'),
  Timestamp('2008-01-23 00:00:00'),
  Timestamp('2008-01-24 00:00:00'),
  Timestamp('2008-01-25 00:00:00'),
  Timestamp('2008-01-26 00:00:00'),
  Timestamp('2008-01-27 00:00:00'),
  Timestamp('2008-01-28 00:00:00'),
  Timestamp('2008-01-29 00:00:00'),
  Timestamp('2008-01-30 00:00:00'),
  Timestamp('2008-01-31 00:00:00'),
  Timestamp('2008-02-01 00:00:00'),
  Timestamp('2008-02-02 00:00:00'),
  Timestamp('2008-02-03 00:00:00')],
 [Timestamp('2008-02-06 00:00:00'),
  Timestamp('2008-02-07 00:00:00'),
  Timestamp('2008-02-08 00:00:00'),
  Timestamp('2008-02-09 00:00:00'),
  Timestamp('2008-02-10 00:00:00'),
  Timestamp('2008-02-11 00:00:00'),
  Timestamp('2008-02-12 00:00:00'),
  Timestamp('2008-02-13 00:00:00')],
 [Timestamp('2008-02-15 00:00:00')],
 [Timestamp('2008-02-18 00:00:00'),
  Timestamp('2008-02-19 00:00:00'),
  Timestamp('2008-02-20 00:00:00'),
  Timestamp('2008-02-21 00:00:00'),
  Timestamp('2008-02-22 00:00:00'),
  Timestamp('2008-02-23 00:00:00'),
  Timestamp('2008-02-24 00:00:00')],
 [Timestamp('2008-03-04 00:00:00')],
 [Timestamp('2008-03-06 00:00:00'),
  Timestamp('2008-03-07 00:00:00'),
  Timestamp('2008-03-08 00:00:00'),
  Timestamp('2008-03-09 00:00:00'),
  Timestamp('2008-03-10 00:00:00'),
  Timestamp('2008-03-11 00:00:00'),
  Timestamp('2008-03-12 00:00:00'),
  Timestamp('2008-03-13 00:00:00'),
  Timestamp('2008-03-14 00:00:00'),
  Timestamp('2008-03-15 00:00:00'),
  Timestamp('2008-03-16 00:00:00')],
 [Timestamp('2008-03-18 00:00:00'),
  Timestamp('2008-03-19 00:00:00'),
  Timestamp('2008-03-20 00:00:00'),
  Timestamp('2008-03-21 00:00:00'),
  Timestamp('2008-03-22 00:00:00'),
  Timestamp('2008-03-23 00:00:00'),
  Timestamp('2008-03-24 00:00:00'),
  Timestamp('2008-03-25 00:00:00'),
  Timestamp('2008-03-26 00:00:00')],
 [Timestamp('2008-04-11 00:00:00'),
  Timestamp('2008-04-12 00:00:00'),
  Timestamp('2008-04-13 00:00:00'),
  Timestamp('2008-04-14 00:00:00'),
  Timestamp('2008-04-15 00:00:00')],
 [Timestamp('2008-04-18 00:00:00'),
  Timestamp('2008-04-19 00:00:00'),
  Timestamp('2008-04-20 00:00:00'),
  Timestamp('2008-04-21 00:00:00'),
  Timestamp('2008-04-22 00:00:00'),
  Timestamp('2008-04-23 00:00:00'),
  Timestamp('2008-04-24 00:00:00'),
  Timestamp('2008-04-25 00:00:00')],
 [Timestamp('2008-05-03 00:00:00'),
  Timestamp('2008-05-04 00:00:00'),
  Timestamp('2008-05-05 00:00:00'),
  Timestamp('2008-05-06 00:00:00')],
 [Timestamp('2008-05-08 00:00:00'),
  Timestamp('2008-05-09 00:00:00'),
  Timestamp('2008-05-10 00:00:00'),
  Timestamp('2008-05-11 00:00:00')],
 [Timestamp('2008-05-13 00:00:00'),
  Timestamp('2008-05-14 00:00:00'),
  Timestamp('2008-05-15 00:00:00'),
  Timestamp('2008-05-16 00:00:00'),
  Timestamp('2008-05-17 00:00:00'),
  Timestamp('2008-05-18 00:00:00'),
  Timestamp('2008-05-19 00:00:00'),
  Timestamp('2008-05-20 00:00:00'),
  Timestamp('2008-05-21 00:00:00'),
  Timestamp('2008-05-22 00:00:00'),
  Timestamp('2008-05-23 00:00:00'),
  Timestamp('2008-05-24 00:00:00'),
  Timestamp('2008-05-25 00:00:00')],
 [Timestamp('2008-06-03 00:00:00')],
 [Timestamp('2008-06-06 00:00:00'), Timestamp('2008-06-07 00:00:00')],
 [Timestamp('2008-06-09 00:00:00'),
  Timestamp('2008-06-10 00:00:00'),
  Timestamp('2008-06-11 00:00:00'),
  Timestamp('2008-06-12 00:00:00'),
  Timestamp('2008-06-13 00:00:00'),
  Timestamp('2008-06-14 00:00:00'),
  Timestamp('2008-06-15 00:00:00')],
 [Timestamp('2008-06-17 00:00:00'),
  Timestamp('2008-06-18 00:00:00'),
  Timestamp('2008-06-19 00:00:00'),
  Timestamp('2008-06-20 00:00:00'),
  Timestamp('2008-06-21 00:00:00'),
  Timestamp('2008-06-22 00:00:00')],
 [Timestamp('2008-07-03 00:00:00'),
  Timestamp('2008-07-04 00:00:00'),
  Timestamp('2008-07-05 00:00:00'),
  Timestamp('2008-07-06 00:00:00')],
 [Timestamp('2008-07-08 00:00:00'),
  Timestamp('2008-07-09 00:00:00'),
  Timestamp('2008-07-10 00:00:00'),
  Timestamp('2008-07-11 00:00:00'),
  Timestamp('2008-07-12 00:00:00'),
  Timestamp('2008-07-13 00:00:00'),
  Timestamp('2008-07-14 00:00:00'),
  Timestamp('2008-07-15 00:00:00'),
  Timestamp('2008-07-16 00:00:00'),
  Timestamp('2008-07-17 00:00:00'),
  Timestamp('2008-07-18 00:00:00'),
  Timestamp('2008-07-19 00:00:00'),
  Timestamp('2008-07-20 00:00:00'),
  Timestamp('2008-07-21 00:00:00'),
  Timestamp('2008-07-22 00:00:00')],
 [Timestamp('2008-07-24 00:00:00'),
  Timestamp('2008-07-25 00:00:00'),
  Timestamp('2008-07-26 00:00:00')],
 [Timestamp('2008-07-29 00:00:00'),
  Timestamp('2008-07-30 00:00:00'),
  Timestamp('2008-07-31 00:00:00'),
  Timestamp('2008-08-01 00:00:00'),
  Timestamp('2008-08-02 00:00:00')],
 [Timestamp('2008-08-04 00:00:00'), Timestamp('2008-08-05 00:00:00')],
 [Timestamp('2008-08-07 00:00:00')],
 [Timestamp('2008-08-09 00:00:00'), Timestamp('2008-08-10 00:00:00')],
 [Timestamp('2008-08-12 00:00:00'),
  Timestamp('2008-08-13 00:00:00'),
  Timestamp('2008-08-14 00:00:00')],
 [Timestamp('2008-08-17 00:00:00'), Timestamp('2008-08-18 00:00:00')],
 [Timestamp('2008-08-20 00:00:00')],
 [Timestamp('2008-08-29 00:00:00'), Timestamp('2008-08-30 00:00:00')],
 [Timestamp('2008-09-01 00:00:00'),
  Timestamp('2008-09-02 00:00:00'),
  Timestamp('2008-09-03 00:00:00'),
  Timestamp('2008-09-04 00:00:00')],
 [Timestamp('2008-09-06 00:00:00'), Timestamp('2008-09-07 00:00:00')],
 [Timestamp('2008-09-09 00:00:00'), Timestamp('2008-09-10 00:00:00')],
 [Timestamp('2008-09-13 00:00:00'),
  Timestamp('2008-09-14 00:00:00'),
  Timestamp('2008-09-15 00:00:00'),
  Timestamp('2008-09-16 00:00:00'),
  Timestamp('2008-09-17 00:00:00'),
  Timestamp('2008-09-18 00:00:00'),
  Timestamp('2008-09-19 00:00:00'),
  Timestamp('2008-09-20 00:00:00'),
  Timestamp('2008-09-21 00:00:00'),
  Timestamp('2008-09-22 00:00:00'),
  Timestamp('2008-09-23 00:00:00'),
  Timestamp('2008-09-24 00:00:00'),
  Timestamp('2008-09-25 00:00:00'),
  Timestamp('2008-09-26 00:00:00'),
  Timestamp('2008-09-27 00:00:00')],
 [Timestamp('2008-09-29 00:00:00'),
  Timestamp('2008-09-30 00:00:00'),
  Timestamp('2008-10-01 00:00:00')],
 [Timestamp('2008-10-03 00:00:00'),
  Timestamp('2008-10-04 00:00:00'),
  Timestamp('2008-10-05 00:00:00'),
  Timestamp('2008-10-06 00:00:00'),
  Timestamp('2008-10-07 00:00:00'),
  Timestamp('2008-10-08 00:00:00'),
  Timestamp('2008-10-09 00:00:00')],
 [Timestamp('2008-10-13 00:00:00'),
  Timestamp('2008-10-14 00:00:00'),
  Timestamp('2008-10-15 00:00:00'),
  Timestamp('2008-10-16 00:00:00'),
  Timestamp('2008-10-17 00:00:00'),
  Timestamp('2008-10-18 00:00:00'),
  Timestamp('2008-10-19 00:00:00')],
 [Timestamp('2008-10-21 00:00:00'), Timestamp('2008-10-22 00:00:00')],
 [Timestamp('2008-10-24 00:00:00'),
  Timestamp('2008-10-25 00:00:00'),
  Timestamp('2008-10-26 00:00:00'),
  Timestamp('2008-10-27 00:00:00'),
  Timestamp('2008-10-28 00:00:00'),
  Timestamp('2008-10-29 00:00:00'),
  Timestamp('2008-10-30 00:00:00'),
  Timestamp('2008-10-31 00:00:00'),
  Timestamp('2008-11-01 00:00:00'),
  Timestamp('2008-11-02 00:00:00')],
 [Timestamp('2008-11-04 00:00:00')],
 [Timestamp('2008-11-06 00:00:00'),
  Timestamp('2008-11-07 00:00:00'),
  Timestamp('2008-11-08 00:00:00'),
  Timestamp('2008-11-09 00:00:00'),
  Timestamp('2008-11-10 00:00:00'),
  Timestamp('2008-11-11 00:00:00'),
  Timestamp('2008-11-12 00:00:00'),
  Timestamp('2008-11-13 00:00:00')],
 [Timestamp('2008-11-15 00:00:00'),
  Timestamp('2008-11-16 00:00:00'),
  Timestamp('2008-11-17 00:00:00'),
  Timestamp('2008-11-18 00:00:00'),
  Timestamp('2008-11-19 00:00:00')],
 [Timestamp('2008-11-21 00:00:00'),
  Timestamp('2008-11-22 00:00:00'),
  Timestamp('2008-11-23 00:00:00'),
  Timestamp('2008-11-24 00:00:00')],
 [Timestamp('2008-11-26 00:00:00'),
  Timestamp('2008-11-27 00:00:00'),
  Timestamp('2008-11-28 00:00:00')],
 [Timestamp('2008-12-02 00:00:00')],
 [Timestamp('2008-12-05 00:00:00'),
  Timestamp('2008-12-06 00:00:00'),
  Timestamp('2008-12-07 00:00:00')],
 [Timestamp('2008-12-10 00:00:00'),
  Timestamp('2008-12-11 00:00:00'),
  Timestamp('2008-12-12 00:00:00')],
 [Timestamp('2008-12-15 00:00:00'),
  Timestamp('2008-12-16 00:00:00'),
  Timestamp('2008-12-17 00:00:00')],
 [Timestamp('2008-12-19 00:00:00'),
  Timestamp('2008-12-20 00:00:00'),
  Timestamp('2008-12-21 00:00:00'),
  Timestamp('2008-12-22 00:00:00'),
  Timestamp('2008-12-23 00:00:00'),
  Timestamp('2008-12-24 00:00:00'),
  Timestamp('2008-12-25 00:00:00'),
  Timestamp('2008-12-26 00:00:00'),
  Timestamp('2008-12-27 00:00:00'),
  Timestamp('2008-12-28 00:00:00'),
  Timestamp('2008-12-29 00:00:00'),
  Timestamp('2008-12-30 00:00:00'),
  Timestamp('2008-12-31 00:00:00'),
  Timestamp('2009-01-01 00:00:00')],
 [Timestamp('2009-01-05 00:00:00'),
  Timestamp('2009-01-06 00:00:00'),
  Timestamp('2009-01-07 00:00:00'),
  Timestamp('2009-01-08 00:00:00')],
 [Timestamp('2009-01-10 00:00:00'), Timestamp('2009-01-11 00:00:00')],
 [Timestamp('2009-01-13 00:00:00'),
  Timestamp('2009-01-14 00:00:00'),
  Timestamp('2009-01-15 00:00:00'),
  Timestamp('2009-01-16 00:00:00'),
  Timestamp('2009-01-17 00:00:00'),
  Timestamp('2009-01-18 00:00:00'),
  Timestamp('2009-01-19 00:00:00'),
  Timestamp('2009-01-20 00:00:00'),
  Timestamp('2009-01-21 00:00:00'),
  Timestamp('2009-01-22 00:00:00')],
 [Timestamp('2009-01-28 00:00:00'),
  Timestamp('2009-01-29 00:00:00'),
  Timestamp('2009-01-30 00:00:00'),
  Timestamp('2009-01-31 00:00:00'),
  Timestamp('2009-02-01 00:00:00'),
  Timestamp('2009-02-02 00:00:00'),
  Timestamp('2009-02-03 00:00:00'),
  Timestamp('2009-02-04 00:00:00'),
  Timestamp('2009-02-05 00:00:00'),
  Timestamp('2009-02-06 00:00:00'),
  Timestamp('2009-02-07 00:00:00'),
  Timestamp('2009-02-08 00:00:00'),
  Timestamp('2009-02-09 00:00:00'),
  Timestamp('2009-02-10 00:00:00'),
  Timestamp('2009-02-11 00:00:00'),
  Timestamp('2009-02-12 00:00:00')],
 [Timestamp('2009-02-15 00:00:00'),
  Timestamp('2009-02-16 00:00:00'),
  Timestamp('2009-02-17 00:00:00'),
  Timestamp('2009-02-18 00:00:00'),
  Timestamp('2009-02-19 00:00:00'),
  Timestamp('2009-02-20 00:00:00'),
  Timestamp('2009-02-21 00:00:00'),
  Timestamp('2009-02-22 00:00:00'),
  Timestamp('2009-02-23 00:00:00'),
  Timestamp('2009-02-24 00:00:00'),
  Timestamp('2009-02-25 00:00:00'),
  Timestamp('2009-02-26 00:00:00'),
  Timestamp('2009-02-27 00:00:00'),
  Timestamp('2009-02-28 00:00:00'),
  Timestamp('2009-03-01 00:00:00'),
  Timestamp('2009-03-02 00:00:00'),
  Timestamp('2009-03-03 00:00:00'),
  Timestamp('2009-03-04 00:00:00'),
  Timestamp('2009-03-05 00:00:00'),
  Timestamp('2009-03-06 00:00:00'),
  Timestamp('2009-03-07 00:00:00'),
  Timestamp('2009-03-08 00:00:00')],
 [Timestamp('2009-03-11 00:00:00'),
  Timestamp('2009-03-12 00:00:00'),
  Timestamp('2009-03-13 00:00:00'),
  Timestamp('2009-03-14 00:00:00'),
  Timestamp('2009-03-15 00:00:00'),
  Timestamp('2009-03-16 00:00:00'),
  Timestamp('2009-03-17 00:00:00'),
  Timestamp('2009-03-18 00:00:00'),
  Timestamp('2009-03-19 00:00:00')],
 [Timestamp('2009-03-21 00:00:00'),
  Timestamp('2009-03-22 00:00:00'),
  Timestamp('2009-03-23 00:00:00'),
  Timestamp('2009-03-24 00:00:00'),
  Timestamp('2009-03-25 00:00:00')],
 [Timestamp('2009-03-28 00:00:00'),
  Timestamp('2009-03-29 00:00:00'),
  Timestamp('2009-03-30 00:00:00'),
  Timestamp('2009-03-31 00:00:00')],
 [Timestamp('2009-04-02 00:00:00'), Timestamp('2009-04-03 00:00:00')],
 [Timestamp('2009-04-06 00:00:00'),
  Timestamp('2009-04-07 00:00:00'),
  Timestamp('2009-04-08 00:00:00'),
  Timestamp('2009-04-09 00:00:00'),
  Timestamp('2009-04-10 00:00:00'),
  Timestamp('2009-04-11 00:00:00')],
 [Timestamp('2009-04-13 00:00:00'),
  Timestamp('2009-04-14 00:00:00'),
  Timestamp('2009-04-15 00:00:00')],
 [Timestamp('2009-04-19 00:00:00'),
  Timestamp('2009-04-20 00:00:00'),
  Timestamp('2009-04-21 00:00:00')],
 [Timestamp('2009-04-24 00:00:00')],
 [Timestamp('2009-04-26 00:00:00')],
 [Timestamp('2009-04-28 00:00:00'),
  Timestamp('2009-04-29 00:00:00'),
  Timestamp('2009-04-30 00:00:00')],
 [Timestamp('2009-05-03 00:00:00'),
  Timestamp('2009-05-04 00:00:00'),
  Timestamp('2009-05-05 00:00:00'),
  Timestamp('2009-05-06 00:00:00'),
  Timestamp('2009-05-07 00:00:00'),
  Timestamp('2009-05-08 00:00:00'),
  Timestamp('2009-05-09 00:00:00')],
 [Timestamp('2009-05-11 00:00:00'),
  Timestamp('2009-05-12 00:00:00'),
  Timestamp('2009-05-13 00:00:00'),
  Timestamp('2009-05-14 00:00:00'),
  Timestamp('2009-05-15 00:00:00')],
 [Timestamp('2009-05-17 00:00:00'),
  Timestamp('2009-05-18 00:00:00'),
  Timestamp('2009-05-19 00:00:00'),
  Timestamp('2009-05-20 00:00:00'),
  Timestamp('2009-05-21 00:00:00'),
  Timestamp('2009-05-22 00:00:00'),
  Timestamp('2009-05-23 00:00:00')],
 [Timestamp('2009-05-25 00:00:00'),
  Timestamp('2009-05-26 00:00:00'),
  Timestamp('2009-05-27 00:00:00'),
  Timestamp('2009-05-28 00:00:00')],
 [Timestamp('2010-01-23 00:00:00'),
  Timestamp('2010-01-24 00:00:00'),
  Timestamp('2010-01-25 00:00:00')],
 [Timestamp('2010-03-06 00:00:00'), Timestamp('2010-03-07 00:00:00')],
 [Timestamp('2010-03-09 00:00:00')],
 [Timestamp('2010-03-11 00:00:00'),
  Timestamp('2010-03-12 00:00:00'),
  Timestamp('2010-03-13 00:00:00')],
 [Timestamp('2010-03-18 00:00:00')],
 [Timestamp('2010-03-21 00:00:00'), Timestamp('2010-03-22 00:00:00')],
 [Timestamp('2010-03-25 00:00:00')],
 [Timestamp('2010-03-31 00:00:00')],
 [Timestamp('2010-04-09 00:00:00')],
 [Timestamp('2010-04-15 00:00:00'),
  Timestamp('2010-04-16 00:00:00'),
  Timestamp('2010-04-17 00:00:00'),
  Timestamp('2010-04-18 00:00:00'),
  Timestamp('2010-04-19 00:00:00'),
  Timestamp('2010-04-20 00:00:00')],
 [Timestamp('2010-04-24 00:00:00')],
 [Timestamp('2010-04-27 00:00:00'), Timestamp('2010-04-28 00:00:00')],
 [Timestamp('2010-05-05 00:00:00')],
 [Timestamp('2010-05-07 00:00:00'),
  Timestamp('2010-05-08 00:00:00'),
  Timestamp('2010-05-09 00:00:00')],
 [Timestamp('2010-05-15 00:00:00'), Timestamp('2010-05-16 00:00:00')],
 [Timestamp('2010-05-23 00:00:00')],
 [Timestamp('2010-05-25 00:00:00'),
  Timestamp('2010-05-26 00:00:00'),
  Timestamp('2010-05-27 00:00:00'),
  Timestamp('2010-05-28 00:00:00')],
 [Timestamp('2010-05-30 00:00:00'), Timestamp('2010-05-31 00:00:00')],
 [Timestamp('2010-06-03 00:00:00')],
 [Timestamp('2010-06-05 00:00:00'), Timestamp('2010-06-06 00:00:00')],
 [Timestamp('2010-06-17 00:00:00')],
 [Timestamp('2010-06-20 00:00:00'),
  Timestamp('2010-06-21 00:00:00'),
  Timestamp('2010-06-22 00:00:00')],
 [Timestamp('2010-06-24 00:00:00')],
 [Timestamp('2010-06-30 00:00:00')],
 [Timestamp('2010-07-02 00:00:00'), Timestamp('2010-07-03 00:00:00')],
 [Timestamp('2010-07-08 00:00:00')],
 [Timestamp('2010-10-13 00:00:00')],
 [Timestamp('2010-10-20 00:00:00')],
 [Timestamp('2010-10-27 00:00:00')],
 [Timestamp('2010-11-12 00:00:00')],
 [Timestamp('2010-11-14 00:00:00')],
 [Timestamp('2010-11-17 00:00:00'),
  Timestamp('2010-11-18 00:00:00'),
  Timestamp('2010-11-19 00:00:00'),
  Timestamp('2010-11-20 00:00:00'),
  Timestamp('2010-11-21 00:00:00'),
  Timestamp('2010-11-22 00:00:00'),
  Timestamp('2010-11-23 00:00:00'),
  Timestamp('2010-11-24 00:00:00'),
  Timestamp('2010-11-25 00:00:00'),
  Timestamp('2010-11-26 00:00:00')],
 [Timestamp('2010-11-29 00:00:00')],
 [Timestamp('2010-12-02 00:00:00')],
 [Timestamp('2010-12-07 00:00:00'), Timestamp('2010-12-08 00:00:00')],
 [Timestamp('2010-12-11 00:00:00'),
  Timestamp('2010-12-12 00:00:00'),
  Timestamp('2010-12-13 00:00:00')],
 [Timestamp('2010-12-16 00:00:00')],
 [Timestamp('2010-12-19 00:00:00'),
  Timestamp('2010-12-20 00:00:00'),
  Timestamp('2010-12-21 00:00:00'),
  Timestamp('2010-12-22 00:00:00')],
 [Timestamp('2010-12-25 00:00:00'),
  Timestamp('2010-12-26 00:00:00'),
  Timestamp('2010-12-27 00:00:00')],
 [Timestamp('2010-12-29 00:00:00')],
 [Timestamp('2011-01-02 00:00:00'),
  Timestamp('2011-01-03 00:00:00'),
  Timestamp('2011-01-04 00:00:00'),
  Timestamp('2011-01-05 00:00:00'),
  Timestamp('2011-01-06 00:00:00'),
  Timestamp('2011-01-07 00:00:00'),
  Timestamp('2011-01-08 00:00:00')],
 [Timestamp('2011-01-12 00:00:00')],
 [Timestamp('2011-01-16 00:00:00')],
 [Timestamp('2011-01-18 00:00:00')],
 [Timestamp('2011-01-20 00:00:00'),
  Timestamp('2011-01-21 00:00:00'),
  Timestamp('2011-01-22 00:00:00')],
 [Timestamp('2011-01-24 00:00:00'),
  Timestamp('2011-01-25 00:00:00'),
  Timestamp('2011-01-26 00:00:00')],
 [Timestamp('2011-01-28 00:00:00'), Timestamp('2011-01-29 00:00:00')],
 [Timestamp('2011-02-02 00:00:00'),
  Timestamp('2011-02-03 00:00:00'),
  Timestamp('2011-02-04 00:00:00')],
 [Timestamp('2011-02-07 00:00:00')],
 [Timestamp('2011-02-09 00:00:00')],
 [Timestamp('2011-02-11 00:00:00'),
  Timestamp('2011-02-12 00:00:00'),
  Timestamp('2011-02-13 00:00:00'),
  Timestamp('2011-02-14 00:00:00'),
  Timestamp('2011-02-15 00:00:00')],
 [Timestamp('2011-02-17 00:00:00'), Timestamp('2011-02-18 00:00:00')],

In [ ]:
run_lengths = []
for system_id in good_timezone_systems:
    print(f'System {system_id}')
    # see runs of good days
    for met_or_inv in ('None', 'inverter', 'meter'):
        try:
            my_good_days = pd.read_csv(f'./test_results_b/good_days/{system_id}_good_days_{met_or_inv}.csv')
        except FileNotFoundError:
            continue
        except BaseException as e:
            raise e
        my_good_days = my_good_days['date']
        my_good_days = my_good_days.astype('datetime64[s]')
        print(met_or_inv)
        for good_run in good_runs_series(my_good_days):
            run_lengths.append(len(good_run))
run_lengths_df = pd.DataFrame(
    data=run_lengths,
    columns=['run_length']
)
run_lengths_df.value_counts().sort_index()

System 4
None
System 10
None
System 33
None
System 36
None
System 50
None
System 51
None
System 1199
inverter
System 1204
inverter
System 1283
inverter
meter
System 1284
None
System 1289
None
System 1332
inverter
meter
System 4902
inverter
meter
System 4903
inverter
meter

run_length
1             3807
2             1930
3             1147
4              720
5              513
6              347
7              209
8              204
9              133
10             102
11              59
12              39
13              36
14              28
15              22
16              24
17              11
18              12
19               7
20               8
21               3
22               6
23               1
24               2
25               2
26               2
30               1
31               1
33               1
36               1
91               1
Name: count, dtype: int64

In [ ]:
my_counts = run_lengths_df.value_counts().sort_index()

In [ ]:
my_counts.iloc[-19:]

run_length
13            36
14            28
15            22
16            24
17            11
18            12
19             7
20             8
21             3
22             6
23             1
24             2
25             2
26             2
30             1
31             1
33             1
36             1
91             1
Name: count, dtype: int64