# Clean power data, convert to energy data, and save to file for future use

In [1]:
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import date, datetime, timedelta
from itertools import product
from copy import deepcopy
from clean_and_collect_power_data import Clean
#from gen_variable_standard_static import metrics_search_for_two_fragments_df

In [2]:
#systems_cleaned
systems_cleaned = pd.read_csv("../../../data/core/systems_cleaned.csv")
#path to read from
read_from_path = "../../../../data_ds_project/testing_yearly_parquet/testing_yearly_parquet/"
#path to write to
write_to_path = "../../../../data_ds_project/parquet_cleaned_energy"

#make a list of all system_id's to choose from. They will be strings and organized in alphabetical order.
base_path = Path(read_from_path)
all_parquet_systems = [p.name for p in base_path.iterdir() if p.is_dir()]
all_parquet_systems

['10',
 '1199',
 '1200',
 '1201',
 '1202',
 '1203',
 '1204',
 '1208',
 '1214',
 '1217',
 '1219',
 '1221',
 '1223',
 '1225',
 '1231',
 '1239',
 '1244',
 '1246',
 '1248',
 '1249',
 '1250',
 '1252',
 '1253',
 '1254',
 '1255',
 '1256',
 '1257',
 '1258',
 '1261',
 '1263',
 '1264',
 '1265',
 '1266',
 '1268',
 '1269',
 '1270',
 '1271',
 '1272',
 '1273',
 '1274',
 '1275',
 '1276',
 '1277',
 '1278',
 '1283',
 '1284',
 '1289',
 '1300',
 '1307',
 '1308',
 '1310',
 '1314',
 '1318',
 '1319',
 '1321',
 '1325',
 '1326',
 '1329',
 '1332',
 '1367',
 '1368',
 '1369',
 '1403',
 '1418',
 '1419',
 '1420',
 '1422',
 '1423',
 '1430',
 '1431',
 '1432',
 '1433',
 '33',
 '34',
 '35',
 '36',
 '4',
 '4901',
 '4902',
 '4903',
 '50',
 '51']

Time to test -- will do so with system 1200

UPDATE: everything seems to work as intended for this system!

In [3]:
system_id = '1200'
make_energy = Clean(system_id, read_from_path, systems_cleaned, 'inverter', write_to_path)
year = make_energy.years[0]
year

2010

In [4]:
data = make_energy.extract_years_data_parquet(2010)
data

	 now beginning extract_years_data_parquet

                    time  ac_power_kW_inverter  ac_power_kW_meter  year
0    2010-10-03 12:15:12              7.052258                NaN  2010
1    2010-10-03 12:30:12              9.621044                NaN  2010
2    2010-10-03 12:45:12              8.489045                NaN  2010
3    2010-10-03 13:00:13              9.352703                NaN  2010
4    2010-10-03 13:15:13             16.757570                NaN  2010
...                  ...                   ...                ...   ...
3758 2010-12-31 16:15:08              2.930369                NaN  2010
3759 2010-12-31 16:30:08              1.179117                NaN  2010
3760 2010-12-31 16:45:08              0.681800                NaN  2010
3761 2010-12-31 17:00:08              0.029318                NaN  2010
3762 2010-12-31 17:15:09              0.000000                NaN  2010

[3763 rows x 4 columns]

In [5]:
data = make_energy.standardize_dataframe(data)
data

	beginning standardize_dataframe
                    time  ac_power_kW_inverter  ac_power_kW_meter  year
0    2010-10-03 12:15:12              7.052258                NaN  2010
1    2010-10-03 12:30:12              9.621044                NaN  2010
2    2010-10-03 12:45:12              8.489045                NaN  2010
3    2010-10-03 13:00:13              9.352703                NaN  2010
4    2010-10-03 13:15:13             16.757570                NaN  2010
...                  ...                   ...                ...   ...
3758 2010-12-31 16:15:08              2.930369                NaN  2010
3759 2010-12-31 16:30:08              1.179117                NaN  2010
3760 2010-12-31 16:45:08              0.681800                NaN  2010
3761 2010-12-31 17:00:08              0.029318                NaN  2010
3762 2010-12-31 17:15:09              0.000000                NaN  2010

[3763 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                    time  ac_power_kW_inverter
0    2010-10-03 12:15:12              7.052258
1    2010-10-03 12:30:12              9.621044
2    2010-10-03 12:45:12              8.489045
3    2010-10-03 13:00:13              9.352703
4    2010-10-03 13:15:13             16.757570
...                  ...                   ...
3758 2010-12-31 16:15:08              2.930369
3759 2010-12-31 16:30:08              1.179117
3760 2010-12-31 16:45:08              0.681800
3761 2010-12-31 17:00:08              0.029318
3762 2010-12-31 17:15:09              0.000000

[3763 rows x 2 columns]
                    time      power
0    2010-10-03 12:15:12   7.052258
1    2010-10-03 12:30:12   9.621044
2    2010-10-03 12:45:12   8.489045
3    2010-10-03 13:00:13   9.352703
4    2010-10-03 13:15:13  16.757570
...                  ...        ...
3758 2010-12-31 16:15:08   2.930369
3759 2010-12-31 16:30:08   1.179117
3760 2010-12-31 16:45:08   0.681800
3761 2010-12-31 17:00:08   0.029318
3762 2010-12-31 17:15:09   0.000000

[3749 rows x 2 columns]

                    time      power
0    2010-10-03 12:15:12   7.052258
1    2010-10-03 12:30:12   9.621044
2    2010-10-03 12:45:12   8.489045
3    2010-10-03 13:00:13   9.352703
4    2010-10-03 13:15:13  16.757570
...                  ...        ...
3758 2010-12-31 16:15:08   2.930369
3759 2010-12-31 16:30:08   1.179117
3760 2010-12-31 16:45:08   0.681800
3761 2010-12-31 17:00:08   0.029318
3762 2010-12-31 17:15:09   0.000000

[3749 rows x 2 columns]

In [6]:
data = make_energy.remove_small_values(data)
data

	beginning remove_small_values
		 max_dc_capacity = 51.84
       smaller_max = 41.6744453
		 in elif null_or_zero == null

                    time      power
0    2010-10-03 12:15:12   7.052258
1    2010-10-03 12:30:12   9.621044
2    2010-10-03 12:45:12   8.489045
3    2010-10-03 13:00:13   9.352703
4    2010-10-03 13:15:13  16.757570
...                  ...        ...
3756 2010-12-31 15:45:08   4.599939
3757 2010-12-31 16:00:08   4.135736
3758 2010-12-31 16:15:08   2.930369
3759 2010-12-31 16:30:08   1.179117
3760 2010-12-31 16:45:08   0.681800

[3260 rows x 2 columns]

In [7]:
data = make_energy.keep_good_days_only(data)
data

	beginning keep_good_days_only
	beginning good_days
		span_flag done
	ending good_days

                    time     power
0    2010-10-04 08:15:44  0.573328
1    2010-10-04 08:30:44  0.915454
2    2010-10-04 08:45:44  0.954552
3    2010-10-04 09:00:44  1.131823
4    2010-10-04 09:15:44  1.540468
...                  ...       ...
1922 2010-12-31 15:45:08  4.599939
1923 2010-12-31 16:00:08  4.135736
1924 2010-12-31 16:15:08  2.930369
1925 2010-12-31 16:30:08  1.179117
1926 2010-12-31 16:45:08  0.681800

[1927 rows x 2 columns]

In [8]:
data = make_energy.convert_to_energy_LRS(data)
data

                   hour     energy
0   2010-10-04 08:00:00   0.610834
1   2010-10-04 09:00:00   1.570952
2   2010-10-04 10:00:00   2.954328
3   2010-10-04 11:00:00   4.597687
4   2010-10-04 12:00:00   5.529439
..                  ...        ...
513 2010-12-31 12:00:00  18.987894
514 2010-12-31 13:00:00  16.733489
515 2010-12-31 14:00:00  16.882554
516 2010-12-31 15:00:00   7.659260
517 2010-12-31 16:00:00   2.231755

[518 rows x 2 columns]

Now do this for all of system 1200, inverter

In [9]:
system_id = '1200'
make_energy = Clean(system_id, read_from_path, systems_cleaned, 'inverter', write_to_path)
make_energy.clean_all_and_write_to_file()

Now processing system 1200, year 2010.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                    time  ac_power_kW_inverter  ac_power_kW_meter  year
0    2010-10-03 12:15:12              7.052258                NaN  2010
1    2010-10-03 12:30:12              9.621044                NaN  2010
2    2010-10-03 12:45:12              8.489045                NaN  2010
3    2010-10-03 13:00:13              9.352703                NaN  2010
4    2010-10-03 13:15:13             16.757570                NaN  2010
...                  ...                   ...                ...   ...
3758 2010-12-31 16:15:08              2.930369                NaN  2010
3759 2010-12-31 16:30:08              1.179117                NaN  2010
3760 2010-12-31 16:45:08              0.681800                NaN  2010
3761 2010-12-31 17:00:08              0.029318                NaN  2010
3762 2010-12-31 17:15:09              0.000000                NaN  2010

[3763 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                    time  ac_power_kW_inverter
0    2010-10-03 12:15:12              7.052258
1    2010-10-03 12:30:12              9.621044
2    2010-10-03 12:45:12              8.489045
3    2010-10-03 13:00:13              9.352703
4    2010-10-03 13:15:13             16.757570
...                  ...                   ...
3758 2010-12-31 16:15:08              2.930369
3759 2010-12-31 16:30:08              1.179117
3760 2010-12-31 16:45:08              0.681800
3761 2010-12-31 17:00:08              0.029318
3762 2010-12-31 17:15:09              0.000000

[3763 rows x 2 columns]
                    time      power
0    2010-10-03 12:15:12   7.052258
1    2010-10-03 12:30:12   9.621044
2    2010-10-03 12:45:12   8.489045
3    2010-10-03 13:00:13   9.352703
4    2010-10-03 13:15:13  16.757570
...                  ...        ...
3758 2010-12-31 16:15:08   2.930369
3759 2010-12-31 16:30:08   1.179117
3760 2010-12-31 16:45:08   0.681800
3761 2010-12-31 17:00:08   0.029318
3762 2010-12-31 17:15:09   0.000000

[3749 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 51.84
       smaller_max = 41.6744453
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
		span_flag done
	ending good_days
Now processing system 1200, year 2011.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                     time  ac_power_kW_inverter  ac_power_kW_meter  year
0     2011-01-01 07:30:06              0.000574                NaN  2011
1     2011-01-01 07:45:06              0.159709                NaN  2011
2     2011-01-01 08:00:06              0.442825                NaN  2011
3     2011-01-01 08:15:06              1.773831                NaN  2011
4     2011-01-01 08:30:06              3.322117                NaN  2011
...                   ...                   ...                ...   ...
19387 2011-12-31 16:55:33              0.000722                NaN  2011
19388 2011-12-31 17:00:33              0.000000                NaN  2011
19389 2011-12-31 17:05:33              0.000000                NaN  2011
19390 2011-12-31 17:10:34              0.000000                NaN  2011
19391 2011-12-31 17:15:34              0.000000                NaN  2011

[19392 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                     time  ac_power_kW_inverter
0     2011-01-01 07:30:06              0.000574
1     2011-01-01 07:45:06              0.159709
2     2011-01-01 08:00:06              0.442825
3     2011-01-01 08:15:06              1.773831
4     2011-01-01 08:30:06              3.322117
...                   ...                   ...
19387 2011-12-31 16:55:33              0.000722
19388 2011-12-31 17:00:33              0.000000
19389 2011-12-31 17:05:33              0.000000
19390 2011-12-31 17:10:34              0.000000
19391 2011-12-31 17:15:34              0.000000

[19392 rows x 2 columns]
                     time     power
0     2011-01-01 07:30:06  0.000574
1     2011-01-01 07:45:06  0.159709
2     2011-01-01 08:00:06  0.442825
3     2011-01-01 08:15:06  1.773831
4     2011-01-01 08:30:06  3.322117
...                   ...       ...
19387 2011-12-31 16:55:33  0.000722
19388 2011-12-31 17:00:33  0.000000
19389 2011-12-31 17:05:33  0.000000
19390 2011-12-31 17:10:34  0.000000
19391 2011-12-31 17:15:34  0.000000

[19275 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 51.84
       smaller_max = 47.379620700000004
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
		span_flag done
	ending good_days
Now processing system 1200, year 2012.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                     time  ac_power_kW_inverter  ac_power_kW_meter  year
0     2012-01-01 07:15:31                   NaN                NaN  2012
1     2012-01-01 07:20:31              0.000000                NaN  2012
2     2012-01-01 07:25:32              0.000210                NaN  2012
3     2012-01-01 07:30:32              0.017430                NaN  2012
4     2012-01-01 07:35:32              0.106918                NaN  2012
...                   ...                   ...                ...   ...
34004 2012-12-13 16:45:32              0.024229                NaN  2012
34005 2012-12-13 16:50:32              0.000000                NaN  2012
34006 2012-12-13 16:55:32              0.000000                NaN  2012
34007 2012-12-13 17:00:32              0.000000                NaN  2012
34008 2012-12-13 17:05:32              0.000000                NaN  2012

[34009 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                     time  ac_power_kW_inverter
0     2012-01-01 07:15:31                   NaN
1     2012-01-01 07:20:31              0.000000
2     2012-01-01 07:25:32              0.000210
3     2012-01-01 07:30:32              0.017430
4     2012-01-01 07:35:32              0.106918
...                   ...                   ...
34004 2012-12-13 16:45:32              0.024229
34005 2012-12-13 16:50:32              0.000000
34006 2012-12-13 16:55:32              0.000000
34007 2012-12-13 17:00:32              0.000000
34008 2012-12-13 17:05:32              0.000000

[34009 rows x 2 columns]
                     time     power
1     2012-01-01 07:20:31  0.000000
2     2012-01-01 07:25:32  0.000210
3     2012-01-01 07:30:32  0.017430
4     2012-01-01 07:35:32  0.106918
5     2012-01-01 07:40:32  0.203117
...                   ...       ...
34004 2012-12-13 16:45:32  0.024229
34005 2012-12-13 16:50:32  0.000000
34006 2012-12-13 16:55:32  0.000000
34007 2012-12-13 17:00:32  0.000000
34008 2012-12-13 17:05:32  0.000000

[33847 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 51.84
       smaller_max = 48.6627193
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
		span_flag done
	ending good_days
Now processing system 1200, year 2013.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                     time  ac_power_kW_inverter  ac_power_kW_meter  year
0     2013-01-20 16:25:32              3.271555                NaN  2013
1     2013-01-20 16:30:33              3.039195                NaN  2013
2     2013-01-20 16:35:33              2.757586                NaN  2013
3     2013-01-20 16:40:33              2.424857                NaN  2013
4     2013-01-20 16:45:33              2.048286                NaN  2013
...                   ...                   ...                ...   ...
50658 2013-12-31 23:45:00                   NaN               0.02  2013
50659 2013-12-31 23:48:00                   NaN               0.02  2013
50660 2013-12-31 23:51:00                   NaN               0.02  2013
50661 2013-12-31 23:54:00                   NaN               0.02  2013
50662 2013-12-31 23:57:00                   NaN               0.02  2013

[50663 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                     time  ac_power_kW_inverter
0     2013-01-20 16:25:32              3.271555
1     2013-01-20 16:30:33              3.039195
2     2013-01-20 16:35:33              2.757586
3     2013-01-20 16:40:33              2.424857
4     2013-01-20 16:45:33              2.048286
...                   ...                   ...
50658 2013-12-31 23:45:00                   NaN
50659 2013-12-31 23:48:00                   NaN
50660 2013-12-31 23:51:00                   NaN
50661 2013-12-31 23:54:00                   NaN
50662 2013-12-31 23:57:00                   NaN

[50663 rows x 2 columns]
                     time     power
0     2013-01-20 16:25:32  3.271555
1     2013-01-20 16:30:33  3.039195
2     2013-01-20 16:35:33  2.757586
3     2013-01-20 16:40:33  2.424857
4     2013-01-20 16:45:33  2.048286
...                   ...       ...
36111 2013-12-01 16:40:33  0.019981
36114 2013-12-01 16:45:33  0.000000
36116 2013-12-01 16:50:33  0.000000
36119 2013-12-01 16:55:33  0.000000
36122 2013-12-01 17:00:33  0.000000

[35028 rows x 2 columns]
	beginning remove_small_values
		 max_dc_capacity = 51.84
       smaller_max = 48.6414001
		 in elif null_or_zero == null
	beginning keep_good_days_only
	beginning good_days
		span_flag done
	ending good_days

c:\Users\hjpha\anaconda3\envs\erdos_ds_environment\Lib\site-packages\pandas\core\computation\expressions.py:74: RuntimeWarning: invalid value encountered in greater_equal
  return op(left_op, right_op)

Now processing system 1200, year 2014.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW_inverter  ac_power_kW_meter  year
0      2014-01-01 00:00:00                   NaN            0.02000  2014
1      2014-01-01 00:03:00                   NaN            0.02000  2014
2      2014-01-01 00:06:00                   NaN            0.02000  2014
3      2014-01-01 00:09:00                   NaN            0.02000  2014
4      2014-01-01 00:12:00                   NaN            0.02000  2014
...                    ...                   ...                ...   ...
175114 2014-12-31 23:45:00                   NaN            0.00002  2014
175115 2014-12-31 23:48:00                   NaN            0.00002  2014
175116 2014-12-31 23:51:00                   NaN            0.00002  2014
175117 2014-12-31 23:54:00                   NaN            0.00002  2014
175118 2014-12-31 23:57:00                   NaN            0.00002  2014

[174639 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                      time  ac_power_kW_inverter
0      2014-01-01 00:00:00                   NaN
1      2014-01-01 00:03:00                   NaN
2      2014-01-01 00:06:00                   NaN
3      2014-01-01 00:09:00                   NaN
4      2014-01-01 00:12:00                   NaN
...                    ...                   ...
175114 2014-12-31 23:45:00                   NaN
175115 2014-12-31 23:48:00                   NaN
175116 2014-12-31 23:51:00                   NaN
175117 2014-12-31 23:54:00                   NaN
175118 2014-12-31 23:57:00                   NaN

[174639 rows x 2 columns]
Empty DataFrame
Columns: [time, power]
Index: []
Now processing system 1200, year 2015.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW_inverter  ac_power_kW_meter  year
0      2015-01-01 00:00:00                   NaN            0.00002  2015
1      2015-01-01 00:03:00                   NaN            0.00002  2015
2      2015-01-01 00:06:00                   NaN            0.00002  2015
3      2015-01-01 00:09:00                   NaN            0.00002  2015
4      2015-01-01 00:12:00                   NaN            0.00002  2015
...                    ...                   ...                ...   ...
174778 2015-12-31 23:45:00                   NaN            0.00002  2015
174779 2015-12-31 23:48:00                   NaN            0.00002  2015
174780 2015-12-31 23:51:00                   NaN            0.00002  2015
174781 2015-12-31 23:54:00                   NaN            0.00002  2015
174782 2015-12-31 23:57:00                   NaN            0.00002  2015

[174783 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                      time  ac_power_kW_inverter
0      2015-01-01 00:00:00                   NaN
1      2015-01-01 00:03:00                   NaN
2      2015-01-01 00:06:00                   NaN
3      2015-01-01 00:09:00                   NaN
4      2015-01-01 00:12:00                   NaN
...                    ...                   ...
174778 2015-12-31 23:45:00                   NaN
174779 2015-12-31 23:48:00                   NaN
174780 2015-12-31 23:51:00                   NaN
174781 2015-12-31 23:54:00                   NaN
174782 2015-12-31 23:57:00                   NaN

[174783 rows x 2 columns]
Empty DataFrame
Columns: [time, power]
Index: []
Now processing system 1200, year 2016.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW_inverter  ac_power_kW_meter  year
0      2016-01-01 00:00:00                   NaN            0.00002  2016
1      2016-01-01 00:03:00                   NaN            0.00002  2016
2      2016-01-01 00:06:00                   NaN            0.00002  2016
3      2016-01-01 00:09:00                   NaN            0.00002  2016
4      2016-01-01 00:12:00                   NaN            0.00002  2016
...                    ...                   ...                ...   ...
110134 2016-12-31 23:35:00                   NaN            0.00002  2016
110135 2016-12-31 23:40:00                   NaN            0.00002  2016
110136 2016-12-31 23:45:00                   NaN            0.00002  2016
110137 2016-12-31 23:50:00                   NaN            0.00002  2016
110138 2016-12-31 23:55:00                   NaN            0.00002  2016

[110139 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                      time  ac_power_kW_inverter
0      2016-01-01 00:00:00                   NaN
1      2016-01-01 00:03:00                   NaN
2      2016-01-01 00:06:00                   NaN
3      2016-01-01 00:09:00                   NaN
4      2016-01-01 00:12:00                   NaN
...                    ...                   ...
110134 2016-12-31 23:35:00                   NaN
110135 2016-12-31 23:40:00                   NaN
110136 2016-12-31 23:45:00                   NaN
110137 2016-12-31 23:50:00                   NaN
110138 2016-12-31 23:55:00                   NaN

[110139 rows x 2 columns]
Empty DataFrame
Columns: [time, power]
Index: []
Now processing system 1200, year 2017.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW_inverter  ac_power_kW_meter  year
0      2017-01-01 00:00:00                   NaN            0.00002  2017
1      2017-01-01 00:05:00                   NaN            0.00002  2017
2      2017-01-01 00:10:00                   NaN            0.00002  2017
3      2017-01-01 00:15:00                   NaN            0.00002  2017
4      2017-01-01 00:20:00                   NaN            0.00002  2017
...                    ...                   ...                ...   ...
105116 2017-12-31 23:35:00                   NaN            0.00002  2017
105117 2017-12-31 23:40:00                   NaN            0.00002  2017
105118 2017-12-31 23:45:00                   NaN            0.00002  2017
105119 2017-12-31 23:50:00                   NaN            0.00002  2017
105120 2017-12-31 23:55:00                   NaN            0.00002  2017

[105121 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                      time  ac_power_kW_inverter
0      2017-01-01 00:00:00                   NaN
1      2017-01-01 00:05:00                   NaN
2      2017-01-01 00:10:00                   NaN
3      2017-01-01 00:15:00                   NaN
4      2017-01-01 00:20:00                   NaN
...                    ...                   ...
105116 2017-12-31 23:35:00                   NaN
105117 2017-12-31 23:40:00                   NaN
105118 2017-12-31 23:45:00                   NaN
105119 2017-12-31 23:50:00                   NaN
105120 2017-12-31 23:55:00                   NaN

[105121 rows x 2 columns]
Empty DataFrame
Columns: [time, power]
Index: []
Now processing system 1200, year 2018.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW_inverter  ac_power_kW_meter  year
0      2018-01-01 00:00:00                   NaN            0.00002  2018
1      2018-01-01 00:05:00                   NaN            0.00002  2018
2      2018-01-01 00:10:00                   NaN            0.00002  2018
3      2018-01-01 00:15:00                   NaN            0.00002  2018
4      2018-01-01 00:20:00                   NaN            0.00002  2018
...                    ...                   ...                ...   ...
105083 2018-12-31 23:35:00                   NaN            0.02000  2018
105084 2018-12-31 23:40:00                   NaN            0.02000  2018
105085 2018-12-31 23:45:00                   NaN            0.02000  2018
105086 2018-12-31 23:50:00                   NaN            0.02000  2018
105087 2018-12-31 23:55:00                   NaN            0.02000  2018

[105088 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                      time  ac_power_kW_inverter
0      2018-01-01 00:00:00                   NaN
1      2018-01-01 00:05:00                   NaN
2      2018-01-01 00:10:00                   NaN
3      2018-01-01 00:15:00                   NaN
4      2018-01-01 00:20:00                   NaN
...                    ...                   ...
105083 2018-12-31 23:35:00                   NaN
105084 2018-12-31 23:40:00                   NaN
105085 2018-12-31 23:45:00                   NaN
105086 2018-12-31 23:50:00                   NaN
105087 2018-12-31 23:55:00                   NaN

[105088 rows x 2 columns]
Empty DataFrame
Columns: [time, power]
Index: []
Now processing system 1200, year 2019.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                      time  ac_power_kW_inverter  ac_power_kW_meter  year
0      2019-01-01 00:00:00                   NaN               0.02  2019
1      2019-01-01 00:05:00                   NaN               0.02  2019
2      2019-01-01 00:10:00                   NaN               0.02  2019
3      2019-01-01 00:15:00                   NaN               0.02  2019
4      2019-01-01 00:20:00                   NaN               0.02  2019
...                    ...                   ...                ...   ...
105095 2019-12-31 23:35:00                   NaN               0.02  2019
105096 2019-12-31 23:40:00                   NaN               0.02  2019
105097 2019-12-31 23:45:00                   NaN               0.02  2019
105098 2019-12-31 23:50:00                   NaN               0.02  2019
105099 2019-12-31 23:55:00                   NaN               0.02  2019

[105100 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                      time  ac_power_kW_inverter
0      2019-01-01 00:00:00                   NaN
1      2019-01-01 00:05:00                   NaN
2      2019-01-01 00:10:00                   NaN
3      2019-01-01 00:15:00                   NaN
4      2019-01-01 00:20:00                   NaN
...                    ...                   ...
105095 2019-12-31 23:35:00                   NaN
105096 2019-12-31 23:40:00                   NaN
105097 2019-12-31 23:45:00                   NaN
105098 2019-12-31 23:50:00                   NaN
105099 2019-12-31 23:55:00                   NaN

[105100 rows x 2 columns]
Empty DataFrame
Columns: [time, power]
Index: []
Now processing system 1200, year 2020.
	 now beginning extract_years_data_parquet
	beginning standardize_dataframe
                     time  ac_power_kW_inverter  ac_power_kW_meter  year
0     2020-01-01 00:00:00                   NaN               0.02  2020
1     2020-01-01 00:05:00                   NaN               0.02  2020
2     2020-01-01 00:10:00                   NaN               0.02  2020
3     2020-01-01 00:15:00                   NaN               0.02  2020
4     2020-01-01 00:20:00                   NaN               0.02  2020
...                   ...                   ...                ...   ...
59796 2020-07-26 16:40:00                   NaN              29.38  2020
59797 2020-07-26 16:45:00                   NaN              28.30  2020
59798 2020-07-26 16:50:00                   NaN              27.90  2020
59799 2020-07-26 16:55:00                   NaN              27.06  2020
59800 2020-07-26 17:00:00                   NaN              26.60  2020

[59801 rows x 4 columns]
		entered meter_or_inverter == inverter
       col_names = Index(['ac_power_kW_inverter'], dtype='str', name='')
                     time  ac_power_kW_inverter
0     2020-01-01 00:00:00                   NaN
1     2020-01-01 00:05:00                   NaN
2     2020-01-01 00:10:00                   NaN
3     2020-01-01 00:15:00                   NaN
4     2020-01-01 00:20:00                   NaN
...                   ...                   ...
59796 2020-07-26 16:40:00                   NaN
59797 2020-07-26 16:45:00                   NaN
59798 2020-07-26 16:50:00                   NaN
59799 2020-07-26 16:55:00                   NaN
59800 2020-07-26 17:00:00                   NaN

[59801 rows x 2 columns]
Empty DataFrame
Columns: [time, power]
Index: []

In [10]:
make_energy.good_days_df

           date
0    2010-10-04
1    2010-10-05
2    2010-10-06
3    2010-10-07
4    2010-10-08
..          ...
601  2013-11-25
602  2013-11-28
603  2013-11-29
604  2013-11-30
605  2013-12-01

[606 rows x 1 columns]