The goal of this notebook is to perform time series EDA. This is intended as EDA ONLY. (Not testing other classes, not performing data analysis etc.)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.model_selection import TimeSeriesSplit

from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error as rmse

#now more time-series specific things
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import statsmodels.api as sm

import pmdarima as pm

system_ids = [2105, 2107, 7333, 9068] #the relevant ids
#system_id = 2105 #may have to look through them eventually
#path = f'../../../../data_ds_project/systems/prize/{system_id}/'

def systemPath(system_id):
    return f'../../../../data_ds_project/systems/prize/{system_id}/'

In [2]:
#Instead of using all the data/files for EDA, we will use only some
#we begin with a list of inverters, and then add on the meters, to make sure we're choosing from all of the possibilities
individual_data = pd.read_csv('../../../../data_ds_project/systems/prize/new_inverter_names_for_prize_cleaned_power.csv')
individual_data

     system_id                                      old_name  new_name
0         2107                    inv_01_ac_power_inv_149583         0
1         2107                    inv_02_ac_power_inv_149588         1
2         2107                    inv_03_ac_power_inv_149593         2
3         2107                    inv_04_ac_power_inv_149598         3
4         2107                    inv_05_ac_power_inv_149603         4
..         ...                                           ...       ...
141       9068  inverter_module_2.2_ac_power_(kw)_inv_150140         5
142       9068  inverter_module_2.3_ac_power_(kw)_inv_150141         6
143       9068  inverter_module_2.4_ac_power_(kw)_inv_150142         7
144       9068           inverter_1_ac_power_(kw)_inv_150143         8
145       9068           inverter_2_ac_power_(kw)_inv_150144         9

[146 rows x 3 columns]

In [3]:
meters_df = pd.DataFrame({
    'system_id' : [2105, 9068], 
    'old_name' : ['meter','meter'], 
    'new_name' : ['000','000']
})
all_datas = pd.concat([individual_data, meters_df], ignore_index = True)
all_datas

     system_id                                      old_name new_name
0         2107                    inv_01_ac_power_inv_149583        0
1         2107                    inv_02_ac_power_inv_149588        1
2         2107                    inv_03_ac_power_inv_149593        2
3         2107                    inv_04_ac_power_inv_149598        3
4         2107                    inv_05_ac_power_inv_149603        4
..         ...                                           ...      ...
143       9068  inverter_module_2.4_ac_power_(kw)_inv_150142        7
144       9068           inverter_1_ac_power_(kw)_inv_150143        8
145       9068           inverter_2_ac_power_(kw)_inv_150144        9
146       2105                                         meter      000
147       9068                                         meter      000

[148 rows x 3 columns]

In [4]:
#sample 10 of them. Set a random seed too to make this reproducible 
sample_data = all_datas.sample(10, random_state = 10)
sample_data

     system_id                                      old_name new_name
79        7333              sos-03-109-inv1-power-kw__176646       55
124       7333              sos-06-081-inv1-power-kw__176691      100
24        7333              sos-01-001-inv1-power-kw__176591        0
35        7333              sos-01-044-inv1-power-kw__176602       11
85        7333              sos-04-040-inv1-power-kw__176652       61
59        7333              sos-02-026-inv1-power-kw__176626       35
10        2107                    inv_11_ac_power_inv_149633       10
114       7333              sos-05-101-inv1-power-kw__176681       90
140       9068  inverter_module_2.1_ac_power_(kw)_inv_150139        4
144       9068           inverter_1_ac_power_(kw)_inv_150143        8

## Naive model 

Build a naive seasonal model. 

- train test split
- next cycle = average of all previous cycles. (do this by day)

In [18]:
from extract_and_clean import Clean

#run it on all of them! -- but with proportions: amount generated/capacity.
# estimate capacity by using maximum daily average value
all_errors = np.zeros(len(sample_data))
for i in range(len(sample_data)):

    #import file from 0th row

    #file name
    file_name = str(sample_data.iloc[i,0])+"_"
    if sample_data.iloc[i,1]=="meter":
        file_name = file_name + "meter_"
    else:
        file_name = file_name + "inverter_"
    file_name = file_name + str(sample_data.iloc[i,2]).zfill(3) + ".csv"

    df = pd.read_csv(f'../../../../data_ds_project/systems/prize/prize_cleaned_power/{file_name}')
    print(f"System_id = {str(sample_data.iloc[i,0])}")

    #turn strings into daytime
    df['time'] = pd.to_datetime(df['time'])

    #should check whether there are any skipped days
    obj = Clean()
    missing_days = obj.missing_days(df)
    if len(missing_days)!=0:
        print("Missing days: (there is a gap before printed day)")
        display(missing_days)

    #make a reasonable estimate as to the capacity -- I don't think we actually need to do this if we're not trying to extrapolate to new locations
    max = df['power'].max()
    df['proportion'] = df['power']/max

    #train test split
    X_train = df.iloc[:int(0.8*len(df))]
    X_test = df.iloc[int(0.8*len(df)):]

    #k-cross validation, since you gotta
    n_splits = 3
    kfold = TimeSeriesSplit(n_splits = n_splits)

    errors = np.zeros(n_splits) #errors array
    for j,(ind_train, ind_ho) in enumerate(kfold.split(X_train)):
        X_tt = X_train.iloc[ind_train]
        X_tt['power'] = X_tt['power']/max
        X_ho = X_train.iloc[ind_ho]
        y_ho = X_train.iloc[ind_ho,2]/max

        grouped_data_means = pd.DataFrame(X_tt.groupby(X_tt["time"].dt.strftime("%m-%d"))["power"].mean())
        #display(grouped_data_means)
        grouped_data_means = grouped_data_means.squeeze()

        X_ho["month_day"] = X_ho["time"].dt.strftime("%m-%d")
        X_ho["y_pred"] = X_ho["month_day"].map(grouped_data_means)
        y_pred = X_ho['y_pred']
        display(y_pred)
        y_pred[y_pred.isna()]=0 #some of the days are missing -- likely due to low reader output

        errors[j] = rmse(y_pred, y_ho)

    errors
    all_errors[i] = errors.mean()
all_errors

System_id = 7333
Missing days: (there is a gap before printed day)

           time        power date_diff
814  2019-02-08   986.223438   16 days
876  2019-04-17  1551.919883    7 days
952  2019-07-03  1505.328784    2 days
1085 2019-12-19   810.772723   37 days
1087 2020-01-01   145.592523   12 days
1663 2021-08-11  1523.026393   13 days
1729 2021-10-26  1061.640267   11 days
1804 2022-01-14   590.345011    6 days
2026 2022-08-25  1594.252859    2 days

494    0.468118
495    0.428264
496    0.292510
497    0.671993
498    0.774856
         ...
980    0.786038
981    0.732857
982    0.586854
983    0.287656
984    0.469238
Name: y_pred, Length: 491, dtype: float64

985     0.719015
986     0.742444
987     0.715733
988     0.736365
989     0.727284
          ...
1471    0.390260
1472    0.383761
1473    0.467273
1474    0.452992
1475    0.241220
Name: y_pred, Length: 491, dtype: float64

1476    0.454334
1477    0.505155
1478    0.457043
1479    0.553247
1480    0.565803
          ...
1962    0.858238
1963    0.871175
1964    0.848068
1965    0.789533
1966    0.822693
Name: y_pred, Length: 491, dtype: float64

System_id = 7333
Missing days: (there is a gap before printed day)

           time        power date_diff
508  2018-03-28  1655.091185    5 days
875  2019-03-31  1441.889874    2 days
886  2019-04-17  1625.197424    7 days
962  2019-07-03  1588.297902    2 days
1095 2019-12-19   908.159358   37 days
1097 2020-01-01   149.913357   12 days
1673 2021-08-11  1519.354383   13 days
1739 2021-10-26   959.123112   11 days
1814 2022-01-14   574.711490    6 days
2036 2022-08-25  1615.940665    2 days

496    0.270455
497    0.686543
498    0.806187
499    0.822607
500    0.732067
         ...
984    0.876247
985    0.848950
986    0.868111
987    0.857659
988    0.872274
Name: y_pred, Length: 493, dtype: float64

989     0.747907
990     0.781735
991     0.740928
992     0.699806
993     0.588869
          ...
1477    0.227253
1478    0.213952
1479    0.284888
1480    0.255998
1481    0.413279
Name: y_pred, Length: 493, dtype: float64

1482    0.331482
1483    0.438552
1484    0.432819
1485    0.399891
1486    0.502845
          ...
1970    0.869419
1971    0.873490
1972    0.851537
1973    0.863040
1974    0.861646
Name: y_pred, Length: 493, dtype: float64

System_id = 7333
Missing days: (there is a gap before printed day)

           time        power date_diff
209  2017-06-19   970.172826   22 days
383  2017-12-11   699.420002    2 days
471  2018-03-27  1444.519848   19 days
851  2019-04-17  1603.036777    7 days
927  2019-07-03  1560.783995    2 days
1060 2019-12-19   898.767767   37 days
1062 2020-01-01   142.678362   12 days
1137 2020-03-21   379.735667    6 days
1633 2021-08-11  1491.705768   13 days
1699 2021-10-26   884.486200   11 days
1774 2022-01-14   543.028665    6 days
1996 2022-08-25  1591.615025    2 days
2379 2023-09-13  1545.821419    2 days
2380 2023-09-28  1509.675037   15 days
2381 2023-10-02  1589.859921    4 days
2390 2023-10-16  1383.904568    6 days
2391 2023-10-31  1119.226642   15 days

479    0.885791
480    0.690590
481    0.130382
482    0.228207
483    0.649791
         ...
952    0.906006
953    0.919878
954    0.924768
955    0.911357
956    0.855891
Name: y_pred, Length: 478, dtype: float64

957     0.744817
958     0.606373
959     0.664491
960     0.785751
961     0.828974
          ...
1430    0.185019
1431    0.152903
1432    0.304576
1433    0.282725
1434    0.400854
Name: y_pred, Length: 478, dtype: float64

1435    0.365063
1436    0.233916
1437    0.327645
1438    0.277368
1439    0.322231
          ...
1908    0.683610
1909    0.567514
1910    0.786859
1911    0.663931
1912    0.754224
Name: y_pred, Length: 478, dtype: float64

System_id = 7333
Missing days: (there is a gap before printed day)

           time        power date_diff
245  2017-07-13  1583.094043   10 days
841  2019-03-05   329.441503    5 days
878  2019-04-17  1616.932250    7 days
954  2019-07-03  1577.372795    2 days
1087 2019-12-19   891.126143   37 days
1089 2020-01-01   142.551667   12 days
1665 2021-08-11  1387.596510   13 days
1731 2021-10-26   893.255897   11 days
1806 2022-01-14   542.989137    6 days
2028 2022-08-25  1621.115549    2 days

492    0.823288
493    0.547380
494    0.316339
495    0.501255
496    0.548135
         ...
979    0.897193
980    0.906424
981    0.908167
982    0.896322
983    0.845058
Name: y_pred, Length: 492, dtype: float64

984     0.742570
985     0.614736
986     0.679752
987     0.788327
988     0.826674
          ...
1471    0.304741
1472    0.276798
1473    0.421178
1474    0.438624
1475    0.515326
Name: y_pred, Length: 492, dtype: float64

1476    0.446407
1477    0.420773
1478    0.510455
1479    0.558415
1480    0.491891
          ...
1963    0.918949
1964    0.899222
1965    0.918388
1966    0.897571
1967    0.835535
Name: y_pred, Length: 492, dtype: float64

System_id = 7333
Missing days: (there is a gap before printed day)

           time        power date_diff
879  2019-03-31  1431.364866    2 days
890  2019-04-17  1622.849060    7 days
966  2019-07-03  1565.171676    2 days
1099 2019-12-19   898.805629   37 days
1101 2020-01-01   136.846588   12 days
1621 2021-06-07   638.393769    4 days
1622 2021-06-10  1343.628644    3 days
1672 2021-08-11  1488.139901   13 days
1738 2021-10-26  1064.104216   11 days
1813 2022-01-14   552.838426    6 days
2035 2022-08-25  1662.355189    2 days

495    0.405812
496    0.235155
497    0.641595
498    0.697356
499    0.696721
         ...
983    0.905584
984    0.907482
985    0.857881
986    0.857049
987    0.842805
Name: y_pred, Length: 493, dtype: float64

988     0.860733
989     0.824093
990     0.829386
991     0.820019
992     0.816692
          ...
1476    0.272855
1477    0.255745
1478    0.375311
1479    0.353026
1480    0.254158
Name: y_pred, Length: 493, dtype: float64

1481    0.313754
1482    0.234127
1483    0.293470
1484    0.252126
1485    0.326750
          ...
1969    0.872041
1970    0.878682
1971    0.857444
1972    0.874096
1973    0.858220
Name: y_pred, Length: 493, dtype: float64

System_id = 7333
Missing days: (there is a gap before printed day)

           time        power date_diff
404  2017-12-11   695.506493    2 days
557  2018-05-14    43.634501    2 days
889  2019-04-17  1606.676952    7 days
965  2019-07-03  1550.381227    2 days
1098 2019-12-19   819.226611   37 days
1100 2020-01-01   145.898205   12 days
1175 2020-03-24   401.991226    9 days
1668 2021-08-11  1485.604938   13 days
1734 2021-10-26   912.922413   11 days
1809 2022-01-14   567.239206    6 days
2031 2022-08-25  1616.619481    2 days

495    0.267463
496    0.711374
497    0.825313
498    0.835267
499    0.749166
         ...
982    0.857849
983    0.886956
984    0.874596
985    0.874990
986    0.865652
Name: y_pred, Length: 492, dtype: float64

987     0.871362
988     0.826114
989     0.839857
990     0.835088
991     0.825916
          ...
1474    0.292544
1475    0.263206
1476    0.418682
1477    0.417599
1478    0.490585
Name: y_pred, Length: 492, dtype: float64

1479    0.441787
1480    0.395226
1481    0.512753
1482    0.559522
1483    0.497436
          ...
1966    0.892558
1967    0.875106
1968    0.887430
1969    0.871438
1970    0.810272
Name: y_pred, Length: 492, dtype: float64

System_id = 2107
Missing days: (there is a gap before printed day)

           time      power date_diff
30   2017-12-02   4.598333    2 days
34   2017-12-07  17.896887    2 days
40   2017-12-14  17.778266    2 days
45   2017-12-20  16.682346    2 days
142  2018-03-30  13.509552    4 days
143  2018-04-03   8.363027    4 days
354  2018-11-08  16.354568    9 days
1165 2021-01-28   5.688845    2 days
1552 2022-03-07  21.506779   17 days
1645 2022-06-17  17.293729   10 days

431    0.183050
432    0.581273
433    0.476780
434    0.819478
435    0.856060
         ...
855    0.709582
856    0.951606
857    0.927871
858    0.923500
859         NaN
Name: y_pred, Length: 429, dtype: float64

860     0.429118
861     0.896596
862     0.778315
863     0.851816
864     0.417546
          ...
1284    0.771205
1285    0.833193
1286    0.798357
1287    0.677105
1288    0.816791
Name: y_pred, Length: 429, dtype: float64

1289    0.814376
1290    0.788983
1291    0.793900
1292    0.803701
1293    0.804734
          ...
1713    0.701851
1714    0.688471
1715    0.709854
1716    0.747876
1717    0.720976
Name: y_pred, Length: 429, dtype: float64

System_id = 7333
Missing days: (there is a gap before printed day)

           time        power date_diff
559  2018-05-17  1729.460654    4 days
876  2019-03-31  1267.722692    2 days
887  2019-04-17  1561.082798    7 days
963  2019-07-03  1521.179726    2 days
1096 2019-12-19   888.796663   37 days
1098 2020-01-01   151.002072   12 days
1674 2021-08-11  1447.993782   13 days
1740 2021-10-26   974.745500   11 days
1815 2022-01-14   593.505582    6 days
2037 2022-08-25  1542.900491    2 days

494    0.510102
495    0.434394
496    0.279899
497    0.682583
498    0.789701
         ...
983    0.828836
984    0.818523
985    0.848205
986    0.820925
987    0.836224
Name: y_pred, Length: 494, dtype: float64

988     0.793818
989     0.788885
990     0.721849
991     0.754747
992     0.707428
          ...
1477    0.244506
1478    0.239192
1479    0.213660
1480    0.277803
1481    0.238814
Name: y_pred, Length: 494, dtype: float64

1482    0.317873
1483    0.317280
1484    0.420461
1485    0.420875
1486    0.370879
          ...
1971    0.831218
1972    0.839344
1973    0.831259
1974    0.833445
1975    0.824973
Name: y_pred, Length: 494, dtype: float64

System_id = 9068
Missing days: (there is a gap before printed day)

           time       power date_diff
2    2017-08-28  366.174667    3 days
12   2017-09-09  249.732143    3 days
15   2017-09-13  118.927778    2 days
25   2017-09-24  129.712500    2 days
40   2017-10-10  321.529851    2 days
57   2017-10-30  165.132632    4 days
69   2017-11-13  276.359223    3 days
139  2018-01-27  163.943137    6 days
142  2018-01-31  243.286905    2 days
151  2018-02-11  222.209091    3 days
159  2018-02-20  208.188608    2 days
211  2018-04-14  415.729545    2 days
288  2018-07-02  389.660870    3 days
960  2020-05-15  217.359341   12 days
1265 2021-03-17  390.140000    2 days
1269 2021-03-22  161.085714    2 days
1353 2021-06-16  189.155882    3 days
1398 2021-08-10  343.600000   11 days
1399 2021-08-12  370.403659    2 days
1401 2021-08-25  407.150495   12 days
1671 2022-05-23  320.541912    2 days
1803 2022-10-03  324.235135    2 days
1929 2023-02-07  347.087129    2 days
1977 2023-03-28  352.027027    2 days
2037 2023-05-31  156.457407    5 days
2040 2023-06-05  343.259406    3 days
2051 2023-06-19  405.450000    4 days
2099 2023-08-08  299.901980    3 days
2111 2023-08-22  372.997590    3 days
2124 2023-09-05  325.119608    2 days
2129 2023-09-13  291.358621    4 days
2194 2024-01-01  176.129412   46 days
2197 2024-01-05  175.661644    2 days
2290 2024-04-08  342.658333    2 days
2351 2024-06-10  283.727957    3 days
2438 2024-09-06  287.141176    2 days
2439 2024-09-09   86.594915    3 days
2442 2024-09-20  138.165306    9 days
2632 2025-03-30   93.953175    2 days

535     0.897943
536     0.890646
537     0.863641
538     0.643194
539     0.685951
          ...
1062    0.514099
1063    0.820609
1064    0.778840
1065    0.767844
1066    0.803031
Name: y_pred, Length: 532, dtype: float64

1067    0.663704
1068    0.671257
1069    0.762547
1070    0.746315
1071    0.535446
          ...
1594    0.691235
1595    0.661173
1596    0.697959
1597    0.704908
1598    0.692028
Name: y_pred, Length: 532, dtype: float64

1599    0.608621
1600    0.481978
1601    0.316452
1602    0.487985
1603    0.683932
          ...
2126    0.574206
2127    0.506446
2128    0.582243
2129    0.647085
2130    0.687107
Name: y_pred, Length: 532, dtype: float64

System_id = 9068
Missing days: (there is a gap before printed day)

           time        power date_diff
2    2017-08-28  1362.256410    3 days
12   2017-09-15   140.086957    9 days
69   2017-11-13   972.534884    3 days
138  2018-01-24   856.000000    4 days
295  2018-07-02  1215.803922    3 days
1282 2021-03-23  1130.113636    9 days
1317 2021-04-28  1215.985075    2 days
1364 2021-06-16   842.052632    3 days
1368 2021-06-21  1403.489796    2 days
1408 2021-08-01  1289.000000    2 days
1635 2022-04-03   845.284672   19 days
1684 2022-05-23  1286.860294    2 days
1816 2022-10-03  1313.040541    2 days
1936 2023-02-01  1199.111111    2 days
1938 2023-02-07  1234.740000    5 days
1980 2023-03-22   374.140351    2 days
1985 2023-03-28  1708.500000    2 days
1986 2023-03-30   856.195402    2 days
1996 2023-04-11  1540.505376    3 days
2042 2023-05-30  1340.910000    4 days
2046 2023-06-05  1170.133333    3 days
2057 2023-06-19  1585.245763    4 days
2062 2023-06-26  1589.777778    3 days
2093 2023-07-28   531.840580    2 days
2102 2023-08-08  1163.941748    3 days
2114 2023-08-22  1455.835294    3 days
2133 2023-09-13  1247.155172    4 days
2157 2023-10-12   624.512821    6 days
2181 2023-11-09  1028.755102    5 days
2189 2024-01-01   747.708738   46 days
2204 2024-01-17   905.493333    2 days
2285 2024-04-08  1416.066667    2 days
2346 2024-06-10  1099.742574    3 days
2598 2025-02-19   993.555556    3 days
2636 2025-03-30   389.374046    2 days

535     0.826088
536     0.627502
537     0.782580
538     0.840891
539     0.833943
          ...
1063    0.739416
1064    0.876925
1065    0.869431
1066    0.881791
1067    0.852087
Name: y_pred, Length: 533, dtype: float64

1068    0.875675
1069    0.754275
1070    0.811019
1071    0.610348
1072    0.557782
          ...
1596    0.628625
1597    0.251634
1598    0.297792
1599    0.459355
1600    0.271348
Name: y_pred, Length: 533, dtype: float64

1601    0.334581
1602    0.436756
1603    0.363936
1604    0.442473
1605    0.425226
          ...
2129    0.666349
2130    0.613675
2131    0.542096
2132    0.683481
2133    0.816261
Name: y_pred, Length: 533, dtype: float64

array([0.6244654 , 0.64054464, 0.65276626, 0.66692999, 0.63578147,
       0.65462245, 0.67285904, 0.62201025, 0.61897596, 0.62099568])