In [1]:
import pandas as pd

df10 = pd.read_csv('10_None.csv')
df50 = pd.read_csv('50_None.csv')
df51 = pd.read_csv('51_None.csv')

In [ ]:
df = df10

summary = pd.DataFrame({
    "mean": df.mean(axis=0),
    "median": df.median(axis=0),
    "max": df.max(axis=0),
    "std": df.std(axis=0)
})

summary = summary.reset_index()
summary = summary.rename(columns={"index": "hyperparameters"})

# sort by mean
summary = summary.sort_values("mean")

summary.head(25)

#looks like 41/33/25

            hyperparameters      mean    median       max       std
64  (31, 10, 0.1, 0.8, 0.8)  0.038613  0.025244  0.224170  0.038050
56   (31, 7, 0.1, 0.8, 0.8)  0.038613  0.025244  0.224170  0.038050
50   (31, 5, 0.1, 1.0, 0.8)  0.038852  0.025964  0.262199  0.038669
66  (31, 10, 0.1, 1.0, 0.8)  0.038997  0.025899  0.265036  0.039023
58   (31, 7, 0.1, 1.0, 0.8)  0.039034  0.025899  0.265036  0.039028
41  (15, 10, 0.1, 0.8, 1.0)  0.039193  0.026894  0.197438  0.037535
33   (15, 7, 0.1, 0.8, 1.0)  0.039193  0.026894  0.197438  0.037535
25   (15, 5, 0.1, 0.8, 1.0)  0.039193  0.026894  0.197438  0.037535
42  (15, 10, 0.1, 1.0, 0.8)  0.039199  0.027670  0.219938  0.037110
34   (15, 7, 0.1, 1.0, 0.8)  0.039199  0.027670  0.219938  0.037110
26   (15, 5, 0.1, 1.0, 0.8)  0.039215  0.027670  0.219938  0.037109
17   (7, 10, 0.1, 0.8, 1.0)  0.039268  0.026775  0.201581  0.036570
1     (7, 5, 0.1, 0.8, 1.0)  0.039268  0.026775  0.201581  0.036570
9     (7, 7, 0.1, 0.8, 1.0)  0.039268  0.026775  0.201581  0.036570
8     (7, 7, 0.1, 0.8, 0.8)  0.039327  0.027345  0.197545  0.035720
16   (7, 10, 0.1, 0.8, 0.8)  0.039327  0.027345  0.197545  0.035720
0     (7, 5, 0.1, 0.8, 0.8)  0.039327  0.027345  0.197545  0.035720
38   (15, 7, 0.2, 1.0, 0.8)  0.039344  0.026731  0.322822  0.039648
46  (15, 10, 0.2, 1.0, 0.8)  0.039344  0.026731  0.322822  0.039648
48   (31, 5, 0.1, 0.8, 0.8)  0.039382  0.026956  0.219395  0.038766
65  (31, 10, 0.1, 0.8, 1.0)  0.039383  0.026903  0.221619  0.038920
57   (31, 7, 0.1, 0.8, 1.0)  0.039383  0.026903  0.221619  0.038920
70  (31, 10, 0.2, 1.0, 0.8)  0.039406  0.027617  0.305668  0.039551
30   (15, 5, 0.2, 1.0, 0.8)  0.039436  0.026731  0.322822  0.039683
18   (7, 10, 0.1, 1.0, 0.8)  0.039469  0.028194  0.182286  0.035651

In [ ]:
df = df50

summary = pd.DataFrame({
    "mean": df.mean(axis=0),
    "median": df.median(axis=0),
    "max": df.max(axis=0),
    "std": df.std(axis=0)
})

summary = summary.reset_index()
summary = summary.rename(columns={"index": "hyperparameters"})

# sort by mean
summary = summary.sort_values("mean")

summary.head(25)

#56

            hyperparameters      mean    median        max       std
56   (31, 7, 0.1, 0.8, 0.8)  1.041629  0.648082   8.887016  1.206276
64  (31, 10, 0.1, 0.8, 0.8)  1.041629  0.648082   8.887016  1.206276
48   (31, 5, 0.1, 0.8, 0.8)  1.044358  0.661424  10.125450  1.249473
50   (31, 5, 0.1, 1.0, 0.8)  1.053864  0.657174   8.290764  1.212296
70  (31, 10, 0.2, 1.0, 0.8)  1.055668  0.719831  12.391276  1.316222
62   (31, 7, 0.2, 1.0, 0.8)  1.055668  0.719831  12.391276  1.316222
49   (31, 5, 0.1, 0.8, 1.0)  1.062772  0.683731   8.632997  1.242011
59   (31, 7, 0.1, 1.0, 1.0)  1.067032  0.662163  11.420413  1.329072
67  (31, 10, 0.1, 1.0, 1.0)  1.067060  0.662163  11.420413  1.329051
66  (31, 10, 0.1, 1.0, 0.8)  1.069974  0.680824   9.631338  1.258014
58   (31, 7, 0.1, 1.0, 0.8)  1.069974  0.680824   9.631338  1.258014
26   (15, 5, 0.1, 1.0, 0.8)  1.070529  0.623039  12.100087  1.320613
34   (15, 7, 0.1, 1.0, 0.8)  1.070529  0.623039  12.100087  1.320613
42  (15, 10, 0.1, 1.0, 0.8)  1.070529  0.623039  12.100087  1.320613
54   (31, 5, 0.2, 1.0, 0.8)  1.071220  0.705590  10.632072  1.306044
27   (15, 5, 0.1, 1.0, 1.0)  1.077147  0.646834  12.563427  1.349344
35   (15, 7, 0.1, 1.0, 1.0)  1.077147  0.646834  12.563427  1.349344
43  (15, 10, 0.1, 1.0, 1.0)  1.077147  0.646834  12.563427  1.349344
24   (15, 5, 0.1, 0.8, 0.8)  1.079705  0.631688  14.177908  1.368394
32   (15, 7, 0.1, 0.8, 0.8)  1.079705  0.631688  14.177908  1.368394
40  (15, 10, 0.1, 0.8, 0.8)  1.079705  0.631688  14.177908  1.368394
47  (15, 10, 0.2, 1.0, 1.0)  1.080186  0.702977   9.859879  1.291027
39   (15, 7, 0.2, 1.0, 1.0)  1.080186  0.702977   9.859879  1.291027
31   (15, 5, 0.2, 1.0, 1.0)  1.080186  0.702977   9.859879  1.291027
57   (31, 7, 0.1, 0.8, 1.0)  1.080557  0.672237  10.168025  1.284359

In [ ]:
df = df51

summary = pd.DataFrame({
    "mean": df.mean(axis=0),
    "median": df.median(axis=0),
    "max": df.max(axis=0),
    "std": df.std(axis=0)
})

summary = summary.reset_index()
summary = summary.rename(columns={"index": "hyperparameters"})

# sort by mean
summary = summary.sort_values("mean")

summary.head(25)

#48

            hyperparameters      mean    median       max       std
50   (31, 5, 0.1, 1.0, 0.8)  1.086789  0.780459  6.236039  1.011577
58   (31, 7, 0.1, 1.0, 0.8)  1.093888  0.730703  6.037259  1.035643
66  (31, 10, 0.1, 1.0, 0.8)  1.094856  0.730703  6.037259  1.040642
59   (31, 7, 0.1, 1.0, 1.0)  1.096101  0.768542  6.074568  1.040104
67  (31, 10, 0.1, 1.0, 1.0)  1.096101  0.768542  6.074568  1.040104
48   (31, 5, 0.1, 0.8, 0.8)  1.098982  0.732446  5.655392  1.016659
56   (31, 7, 0.1, 0.8, 0.8)  1.100136  0.756980  6.097769  1.035525
64  (31, 10, 0.1, 0.8, 0.8)  1.100136  0.756980  6.097769  1.035525
51   (31, 5, 0.1, 1.0, 1.0)  1.104076  0.750093  5.914262  1.053988
65  (31, 10, 0.1, 0.8, 1.0)  1.110093  0.761613  5.882020  1.049776
57   (31, 7, 0.1, 0.8, 1.0)  1.110288  0.761613  5.882020  1.049838
24   (15, 5, 0.1, 0.8, 0.8)  1.112699  0.800474  6.241013  1.032295
32   (15, 7, 0.1, 0.8, 0.8)  1.112699  0.800474  6.241013  1.032295
40  (15, 10, 0.1, 0.8, 0.8)  1.112699  0.800474  6.241013  1.032295
49   (31, 5, 0.1, 0.8, 1.0)  1.121080  0.750381  6.675079  1.067237
26   (15, 5, 0.1, 1.0, 0.8)  1.135057  0.828149  6.229803  1.070605
34   (15, 7, 0.1, 1.0, 0.8)  1.135057  0.828149  6.229803  1.070605
42  (15, 10, 0.1, 1.0, 0.8)  1.135057  0.828149  6.229803  1.070605
54   (31, 5, 0.2, 1.0, 0.8)  1.137041  0.780198  7.230024  1.152028
52   (31, 5, 0.2, 0.8, 0.8)  1.141683  0.785247  6.953358  1.078180
29   (15, 5, 0.2, 0.8, 1.0)  1.146772  0.769805  6.843449  1.123919
37   (15, 7, 0.2, 0.8, 1.0)  1.147426  0.769805  6.843449  1.123987
45  (15, 10, 0.2, 0.8, 1.0)  1.147426  0.769805  6.843449  1.123987
53   (31, 5, 0.2, 0.8, 1.0)  1.148211  0.804344  7.453479  1.100191
43  (15, 10, 0.1, 1.0, 1.0)  1.155681  0.834448  6.079297  1.084352