Light GBM error comparison

In [4]:
import pandas as pd

df10 = pd.read_csv('10_None.csv')
df50 = pd.read_csv('50_None.csv')
df51 = pd.read_csv('51_None.csv')

System 10

In [20]:
df = df10

summary = pd.DataFrame({
    "mean": df.mean(axis=0),
    "median": df.median(axis=0),
    "max": df.max(axis=0),
    "std": df.std(axis=0)
})

summary = summary.reset_index()
summary = summary.rename(columns={"index": "hyperparameters"})

# sort by mean
summary = summary.sort_values("mean")

display(summary.head(1))
#48
#but 56 isn't too bad

df = df50

summary = pd.DataFrame({
    "mean": df.mean(axis=0),
    "median": df.median(axis=0),
    "max": df.max(axis=0),
    "std": df.std(axis=0)
})

summary = summary.reset_index()
summary = summary.rename(columns={"index": "hyperparameters"})

# sort by mean
summary = summary.sort_values("mean")

display(summary.head(1))
#48
#but 56 isn't that bad
df = df51

summary = pd.DataFrame({
    "mean": df.mean(axis=0),
    "median": df.median(axis=0),
    "max": df.max(axis=0),
    "std": df.std(axis=0)
})

summary = summary.reset_index()
summary = summary.rename(columns={"index": "hyperparameters"})

# sort by mean
summary = summary.sort_values("mean")

summary.head(25)
#56: (31, 5, 0.1, 100, 0.8, 0.8)
summary.loc[summary['hyperparameters']=='(31, 5, 0.1, 100, 0.8, 0.8)']

                 hyperparameters      mean    median       max       std
48  (31, -1, 0.1, 100, 0.8, 0.8)  0.039082  0.025635  0.260873  0.038583

                 hyperparameters      mean    median       max       std
48  (31, -1, 0.1, 100, 0.8, 0.8)  1.019386  0.700245  8.926571  1.129322

                hyperparameters      mean    median       max       std
56  (31, 5, 0.1, 100, 0.8, 0.8)  1.099389  0.784742  5.550183  1.028978

System 50

In [6]:
df = df50

summary = pd.DataFrame({
    "mean": df.mean(axis=0),
    "median": df.median(axis=0),
    "max": df.max(axis=0),
    "std": df.std(axis=0)
})

summary = summary.reset_index()
summary = summary.rename(columns={"index": "hyperparameters"})

# sort by mean
summary = summary.sort_values("mean")

summary.head(25)

#48
#but 56 isn't that bad

                 hyperparameters      mean    median        max       std
48  (31, -1, 0.1, 100, 0.8, 0.8)  1.019386  0.700245   8.926571  1.129322
50  (31, -1, 0.1, 100, 1.0, 0.8)  1.019386  0.700245   8.926571  1.129322
56   (31, 5, 0.1, 100, 0.8, 0.8)  1.024605  0.656397   9.220692  1.124431
58   (31, 5, 0.1, 100, 1.0, 0.8)  1.024804  0.656397   9.220692  1.124655
68   (31, 7, 0.2, 100, 0.8, 0.8)  1.030222  0.667478   9.249678  1.166259
70   (31, 7, 0.2, 100, 1.0, 0.8)  1.030222  0.667478   9.249678  1.166259
24  (15, -1, 0.1, 100, 0.8, 0.8)  1.036749  0.670985   8.005422  1.128024
26  (15, -1, 0.1, 100, 1.0, 0.8)  1.036749  0.670985   8.005422  1.128024
65   (31, 7, 0.1, 100, 0.8, 1.0)  1.042202  0.654376  10.233054  1.263264
67   (31, 7, 0.1, 100, 1.0, 1.0)  1.042202  0.654376  10.233054  1.263264
4    (7, -1, 0.2, 100, 0.8, 0.8)  1.043333  0.680020  10.458571  1.144688
6    (7, -1, 0.2, 100, 1.0, 0.8)  1.043333  0.680020  10.458571  1.144688
20    (7, 7, 0.2, 100, 0.8, 0.8)  1.043333  0.680020  10.458571  1.144688
22    (7, 7, 0.2, 100, 1.0, 0.8)  1.043333  0.680020  10.458571  1.144688
30  (15, -1, 0.2, 100, 1.0, 0.8)  1.043882  0.679710   9.922896  1.157980
28  (15, -1, 0.2, 100, 0.8, 0.8)  1.043882  0.679710   9.922896  1.157980
40   (15, 7, 0.1, 100, 0.8, 0.8)  1.044934  0.670453   8.294098  1.135632
42   (15, 7, 0.1, 100, 1.0, 0.8)  1.044934  0.670453   8.294098  1.135632
54  (31, -1, 0.2, 100, 1.0, 0.8)  1.045205  0.658896  10.182363  1.254707
52  (31, -1, 0.2, 100, 0.8, 0.8)  1.045205  0.658896  10.182363  1.254707
41   (15, 7, 0.1, 100, 0.8, 1.0)  1.045237  0.651150  10.220863  1.229140
43   (15, 7, 0.1, 100, 1.0, 1.0)  1.045237  0.651150  10.220863  1.229140
32   (15, 5, 0.1, 100, 0.8, 0.8)  1.045911  0.666995   8.623106  1.164665
34   (15, 5, 0.1, 100, 1.0, 0.8)  1.045911  0.666995   8.623106  1.164665
49  (31, -1, 0.1, 100, 0.8, 1.0)  1.046451  0.671988  10.082471  1.255207

System 51

In [18]:
df = df51

summary = pd.DataFrame({
    "mean": df.mean(axis=0),
    "median": df.median(axis=0),
    "max": df.max(axis=0),
    "std": df.std(axis=0)
})

summary = summary.reset_index()
summary = summary.rename(columns={"index": "hyperparameters"})

# sort by mean
summary = summary.sort_values("mean")

summary.head(25)
#56: (31, 5, 0.1, 100, 0.8, 0.8)
summary.loc[summary['hyperparameters']=='(31, 5, 0.1, 100, 0.8, 0.8)']

                hyperparameters      mean    median       max       std
56  (31, 5, 0.1, 100, 0.8, 0.8)  1.099389  0.784742  5.550183  1.028978