Light GBM error comparison

In [ ]:
import pandas as pd

df10 = pd.read_csv('10_None.csv')
df50 = pd.read_csv('50_None.csv')
df51 = pd.read_csv('51_None.csv')

System 10

In [ ]:
df = df10

summary = pd.DataFrame({
    "mean": df.mean(axis=0),
    "median": df.median(axis=0),
    "max": df.max(axis=0),
    "std": df.std(axis=0)
})

summary = summary.reset_index()
summary = summary.rename(columns={"index": "hyperparameters"})

# sort by mean
summary = summary.sort_values("mean")

summary.head(25)

#48
#but 56 isn't too bad

                 hyperparameters      mean    median       max       std
48  (31, -1, 0.1, 100, 0.8, 0.8)  0.039082  0.025635  0.260873  0.038583
50  (31, -1, 0.1, 100, 1.0, 0.8)  0.039082  0.025635  0.260873  0.038583
58   (31, 5, 0.1, 100, 1.0, 0.8)  0.039162  0.026248  0.256401  0.038612
56   (31, 5, 0.1, 100, 0.8, 0.8)  0.039162  0.026248  0.256401  0.038612
66   (31, 7, 0.1, 100, 1.0, 0.8)  0.039319  0.026731  0.297139  0.040171
64   (31, 7, 0.1, 100, 0.8, 0.8)  0.039319  0.026731  0.297139  0.040171
67   (31, 7, 0.1, 100, 1.0, 1.0)  0.039339  0.025393  0.289735  0.039621
65   (31, 7, 0.1, 100, 0.8, 1.0)  0.039339  0.025393  0.289735  0.039621
40   (15, 7, 0.1, 100, 0.8, 0.8)  0.039365  0.027034  0.216537  0.037280
42   (15, 7, 0.1, 100, 1.0, 0.8)  0.039365  0.027034  0.216537  0.037280
49  (31, -1, 0.1, 100, 0.8, 1.0)  0.039424  0.025760  0.277442  0.039600
51  (31, -1, 0.1, 100, 1.0, 1.0)  0.039424  0.025760  0.277442  0.039600
34   (15, 5, 0.1, 100, 1.0, 0.8)  0.039511  0.026961  0.237362  0.038095
32   (15, 5, 0.1, 100, 0.8, 0.8)  0.039511  0.026961  0.237362  0.038095
10    (7, 5, 0.1, 100, 1.0, 0.8)  0.039529  0.027546  0.204546  0.036508
8     (7, 5, 0.1, 100, 0.8, 0.8)  0.039529  0.027546  0.204546  0.036508
25  (15, -1, 0.1, 100, 0.8, 1.0)  0.039543  0.026630  0.241109  0.039056
27  (15, -1, 0.1, 100, 1.0, 1.0)  0.039543  0.026630  0.241109  0.039056
24  (15, -1, 0.1, 100, 0.8, 0.8)  0.039587  0.027347  0.254151  0.038389
26  (15, -1, 0.1, 100, 1.0, 0.8)  0.039587  0.027347  0.254151  0.038389
12    (7, 5, 0.2, 100, 0.8, 0.8)  0.039620  0.027007  0.307856  0.038792
14    (7, 5, 0.2, 100, 1.0, 0.8)  0.039620  0.027007  0.307856  0.038792
0    (7, -1, 0.1, 100, 0.8, 0.8)  0.039623  0.027221  0.180219  0.036786
2    (7, -1, 0.1, 100, 1.0, 0.8)  0.039623  0.027221  0.180219  0.036786
18    (7, 7, 0.1, 100, 1.0, 0.8)  0.039623  0.027221  0.180219  0.036786

System 50

In [ ]:
df = df50

summary = pd.DataFrame({
    "mean": df.mean(axis=0),
    "median": df.median(axis=0),
    "max": df.max(axis=0),
    "std": df.std(axis=0)
})

summary = summary.reset_index()
summary = summary.rename(columns={"index": "hyperparameters"})

# sort by mean
summary = summary.sort_values("mean")

summary.head(25)

#48
#but 56 isn't that bad

                 hyperparameters      mean    median        max       std
48  (31, -1, 0.1, 100, 0.8, 0.8)  1.019386  0.700245   8.926571  1.129322
50  (31, -1, 0.1, 100, 1.0, 0.8)  1.019386  0.700245   8.926571  1.129322
56   (31, 5, 0.1, 100, 0.8, 0.8)  1.024605  0.656397   9.220692  1.124431
58   (31, 5, 0.1, 100, 1.0, 0.8)  1.024804  0.656397   9.220692  1.124655
68   (31, 7, 0.2, 100, 0.8, 0.8)  1.030222  0.667478   9.249678  1.166259
70   (31, 7, 0.2, 100, 1.0, 0.8)  1.030222  0.667478   9.249678  1.166259
24  (15, -1, 0.1, 100, 0.8, 0.8)  1.036749  0.670985   8.005422  1.128024
26  (15, -1, 0.1, 100, 1.0, 0.8)  1.036749  0.670985   8.005422  1.128024
65   (31, 7, 0.1, 100, 0.8, 1.0)  1.042202  0.654376  10.233054  1.263264
67   (31, 7, 0.1, 100, 1.0, 1.0)  1.042202  0.654376  10.233054  1.263264
4    (7, -1, 0.2, 100, 0.8, 0.8)  1.043333  0.680020  10.458571  1.144688
6    (7, -1, 0.2, 100, 1.0, 0.8)  1.043333  0.680020  10.458571  1.144688
20    (7, 7, 0.2, 100, 0.8, 0.8)  1.043333  0.680020  10.458571  1.144688
22    (7, 7, 0.2, 100, 1.0, 0.8)  1.043333  0.680020  10.458571  1.144688
30  (15, -1, 0.2, 100, 1.0, 0.8)  1.043882  0.679710   9.922896  1.157980
28  (15, -1, 0.2, 100, 0.8, 0.8)  1.043882  0.679710   9.922896  1.157980
40   (15, 7, 0.1, 100, 0.8, 0.8)  1.044934  0.670453   8.294098  1.135632
42   (15, 7, 0.1, 100, 1.0, 0.8)  1.044934  0.670453   8.294098  1.135632
54  (31, -1, 0.2, 100, 1.0, 0.8)  1.045205  0.658896  10.182363  1.254707
52  (31, -1, 0.2, 100, 0.8, 0.8)  1.045205  0.658896  10.182363  1.254707
41   (15, 7, 0.1, 100, 0.8, 1.0)  1.045237  0.651150  10.220863  1.229140
43   (15, 7, 0.1, 100, 1.0, 1.0)  1.045237  0.651150  10.220863  1.229140
32   (15, 5, 0.1, 100, 0.8, 0.8)  1.045911  0.666995   8.623106  1.164665
34   (15, 5, 0.1, 100, 1.0, 0.8)  1.045911  0.666995   8.623106  1.164665
49  (31, -1, 0.1, 100, 0.8, 1.0)  1.046451  0.671988  10.082471  1.255207

System 51

In [ ]:
df = df51

summary = pd.DataFrame({
    "mean": df.mean(axis=0),
    "median": df.median(axis=0),
    "max": df.max(axis=0),
    "std": df.std(axis=0)
})

summary = summary.reset_index()
summary = summary.rename(columns={"index": "hyperparameters"})

# sort by mean
summary = summary.sort_values("mean")

summary.head(25)

#56: (31, 5, 0.1, 100, 0.8, 0.8)

                 hyperparameters      mean    median       max       std
48  (31, -1, 0.1, 100, 0.8, 0.8)  1.091245  0.787927  7.712657  1.052622
50  (31, -1, 0.1, 100, 1.0, 0.8)  1.091245  0.787927  7.712657  1.052622
30  (15, -1, 0.2, 100, 1.0, 0.8)  1.098208  0.765862  6.802728  1.053108
28  (15, -1, 0.2, 100, 0.8, 0.8)  1.098208  0.765862  6.802728  1.053108
49  (31, -1, 0.1, 100, 0.8, 1.0)  1.098846  0.726125  7.044882  1.066338
51  (31, -1, 0.1, 100, 1.0, 1.0)  1.098846  0.726125  7.044882  1.066338
58   (31, 5, 0.1, 100, 1.0, 0.8)  1.099389  0.784742  5.550183  1.028978
56   (31, 5, 0.1, 100, 0.8, 0.8)  1.099389  0.784742  5.550183  1.028978
24  (15, -1, 0.1, 100, 0.8, 0.8)  1.099448  0.811972  5.867438  1.016096
26  (15, -1, 0.1, 100, 1.0, 0.8)  1.099448  0.811972  5.867438  1.016096
40   (15, 7, 0.1, 100, 0.8, 0.8)  1.105886  0.801739  6.408606  1.036354
42   (15, 7, 0.1, 100, 1.0, 0.8)  1.105886  0.801739  6.408606  1.036354
46   (15, 7, 0.2, 100, 1.0, 0.8)  1.112964  0.786183  6.685274  1.043491
44   (15, 7, 0.2, 100, 0.8, 0.8)  1.112964  0.786183  6.685274  1.043491
66   (31, 7, 0.1, 100, 1.0, 0.8)  1.113741  0.759957  6.699089  1.054323
64   (31, 7, 0.1, 100, 0.8, 0.8)  1.113741  0.759957  6.699089  1.054323
52  (31, -1, 0.2, 100, 0.8, 0.8)  1.115171  0.786970  7.747061  1.101153
54  (31, -1, 0.2, 100, 1.0, 0.8)  1.115171  0.786970  7.747061  1.101153
27  (15, -1, 0.1, 100, 1.0, 1.0)  1.117670  0.783957  6.410271  1.067658
25  (15, -1, 0.1, 100, 0.8, 1.0)  1.117670  0.783957  6.410271  1.067658
21    (7, 7, 0.2, 100, 0.8, 1.0)  1.120257  0.815037  6.481877  1.053019
23    (7, 7, 0.2, 100, 1.0, 1.0)  1.120257  0.815037  6.481877  1.053019
7    (7, -1, 0.2, 100, 1.0, 1.0)  1.120257  0.815037  6.481877  1.053019
5    (7, -1, 0.2, 100, 0.8, 1.0)  1.120257  0.815037  6.481877  1.053019
55  (31, -1, 0.2, 100, 1.0, 1.0)  1.122400  0.807281  6.262700  1.061579